### ISSUE TITLE
Implement precompiled contracts

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#1]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Tuesday May 30, 2017 at 07:50 GMT_
_Originally opened as https://github.com/dapphub/hevm/issues/4_

----

Will need some crypto dependencies etc.

**Comment by ggrieco-tob** [comment]
Is there any estimation on when this could be implemented?

**Comment by asymmetric** [comment]
@livnev AFAIK you've done some work on this.

Do you think it'd make more sense to close this issue and have one for each precompile we plan on implementing?

**Comment by livnev** [comment]
Superseded by #186, #187, #188, #189, #190
