### ISSUE TITLE
dapp: dapp test events do not show values indexed

### ISSUE THREAD

**Issue by gbalabasquer** [dapphub/dapptools#100]
The debug tree doesn't show values which are named as `indexed`.
For example:

`event NewCdp(address indexed guy, address indexed lad, bytes12 cdp);`

It is just printing: `NewCdp(0x000000000000000000000001)`

If I remove `indexed` to those values, all of them are shown.

**Comment by rainbreak** [comment]
I modified the trace for events recently, so I wonder if this is a regression. Do you remember if it used to output all the data?

`indexed` event args are kept separately from the unindexed events, in the `topics` of the log.

**Comment by rainbreak** [comment]
Topics are now emitted.
