### ISSUE TITLE
Update geth from `dapp testnet` to more recent version

### ISSUE THREAD

**Issue by nanexcool** [dapphub/dapptools#120]
Should update to Geth v1.8.22 https://github.com/ethereum/go-ethereum/releases/tag/v1.8.22 and enable Constantinople

**Comment by asymmetric** [comment]
I'm wondering if we even need "geth unlimited" - it can be misleading to see something get mined in `dapp testnet` that wouldn't get mined on mainnet or public testnets due to e.g. hitting the block size limit.

What are some usecases of unlimited?

**Comment by rainbreak** [comment]
`geth unlimited` in principle lets you simulate `dapp test` but on `geth`. You need unlimited size because test contracts are typically huge with lots of deployed contracts.

**Comment by xwvvvvwx** [comment]
What do people think about making it a command line flag (e.g. `dapp testnet --unlimited` if you want `geth unlimited`)?

**Comment by asymmetric** [comment]
I guess then the question is, do we want to use `dapp testnet` to bring up a vanilla geth? Is that better than just running geth?

**Comment by xwvvvvwx** [comment]
`dapp testnet` has some snapshotting helpers that vanilla geth does not provide (although they can be a little unreliable).

**Comment by MrChico** [comment]
geth is now more recent :+1:
