### ISSUE TITLE
create single .sol file

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#14]
<a href="https://github.com/rainbreak"><img src="https://avatars3.githubusercontent.com/u/18486361?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rainbreak](https://github.com/rainbreak)**
_Wednesday Jun 28, 2017 at 12:26 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/32_

----

Compile all libs / sources into a single .sol file. Would be useful for e.g. etherscan verification and anything else that can't deal with multi-file sources.

**Comment by rainbreak** [comment]
`hevm flatten` :+1:
