### ISSUE TITLE
seth: read from stdin

### ISSUE THREAD

**Issue by asymmetric** [dapphub/dapptools#154]
[Some commands](
https://github.com/dapphub/dapptools/tree/d8e78aedaaeda323fb583ea52bef250634399e6a/src/seth/libexec/seth/seth---to-bytes32#L5) are able to read data from `stdin`, whereas most aren't.

I think it would be good to standardize on one way of doing things, and I see a benefit in accepting arguments from `stdin`, in that it makes the data flow more intuitive: `seth --foo | seth --bar` instead of `seth --bar $(seth --foo)`.

**Comment by asymmetric** [comment]
Note that this only makes sense for unary functions, like all of the `--to-*`.

Not sure if we should support it for binary functions where one argument is optional (the `--from-*` ones for example).

**Comment by MrChico** [comment]
closed by #439
