### ISSUE TITLE
-r doesn't seem to work

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#16]
<a href="https://github.com/ryepdx"><img src="https://avatars2.githubusercontent.com/u/691597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryepdx](https://github.com/ryepdx)**
_Tuesday Jul 18, 2017 at 10:31 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/36_

----

With `sai`, there's no difference when I run `dapp test` and when I run `dapp test -r testCascade`.

To prevent regression, there should probably be a test for this bug added to the `selftest`.

**Comment by rainbreak** [comment]
This works again.
