### ISSUE TITLE
hevm: release to stackage?

### ISSUE THREAD

**Issue by rainbreak** [dapphub/dapptools#162]
following on from https://github.com/dapphub/dapptools/issues/34#issuecomment-475673984

@ggrieco-tob

**Comment by desaperados** [comment]
Lets at least update the Hackage version to the latest release: https://hackage.haskell.org/package/hevm

**Comment by desaperados** [comment]
@mbrock ???

**Comment by MrChico** [comment]
As of `hevm 0.41.0`, we are now on back on hackage https://hackage.haskell.org/package/hevm-0.41.0. 
We are still not on Stackage, but I will close this issue anyway. Reopen if stackage is really needed
