### ISSUE TITLE
Logging events

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#17]
<a href="https://github.com/ryepdx"><img src="https://avatars2.githubusercontent.com/u/691597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ryepdx](https://github.com/ryepdx)**
_Monday Aug 07, 2017 at 15:36 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/43_

----

Does not seem to work at present. Added a logging event [per the documentation](https://dapp.readthedocs.io/en/latest/unit_testing.html#logging-events) and am seeing nothing on the console.

**Comment by rainbreak** [comment]
All events are logged in the trace now.
