### ISSUE TITLE
Hex inconsistencies

### ISSUE THREAD

**Issue by asymmetric** [dapphub/dapptools#178]
As mentioned in https://github.com/dapphub/dapptools/issues/170#issuecomment-489329022, there is some inconsistency in how seth outputs hexadecimal numbers.

`seth---to-int256` and `seth---to-uint256` [remove the `0x`](
https://github.com/dapphub/dapptools/tree/cb9cbcdcbe3d7449d122c4543013fa884517113a/src/seth/libexec/seth/seth---to-uint256#L6), whereas `seth---to-hex` [adds it](
https://github.com/dapphub/dapptools/tree/cb9cbcdcbe3d7449d122c4543013fa884517113a/src/seth/libexec/seth/seth---to-hex#L5).

Are there any reasons for this inconsistency? e.g. are there any tools that expect the number with/without the `0x` prefix?

If we decide not to always prepend the `0x`, we should add a mention of the output base in the help of  the commands.

**Comment by rainbreak** [comment]
I think all hex should have the `0x` prefix. If any tools are relying on this not being there then I think they are broken.

**Comment by MrChico** [comment]
Closed by https://github.com/dapphub/dapptools/pull/326
