### ISSUE TITLE
hevm: implement SHA256 (precompile no. 2)

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#186]

**Comment by kmbarry1** [comment]
Any context on this (e.g. a link to a spec)? Is there any time-sensitivity here? I'm not sure how long it would take me, so I want to make sure it isn't blocking anything important before I start working on it.

**Comment by livnev** [comment]
> Any context on this (e.g. a link to a spec)? Is there any time-sensitivity here? I'm not sure how long it would take me, so I want to make sure it isn't blocking anything important before I start working on it.

@kmbarry1  It's not blocking anything that I know of (in fact I don't know if I've ever seen anyone use `SHA256` for anything in all of Ethereum), we just want to get 100% test compliance for `hevm`. The way to do this would be to find a suitable C library implementing `SHA256`, call it from `ethjet` and get it to build and link with `nix`, following the example of `secp256k1` which is already implemented.

**Comment by cmditch** [comment]
See https://github.com/dapphub/dapptools/pull/200

**Comment by rainbreak** [comment]
#213
