### ISSUE TITLE
Error message rounding values [dapp]

### ISSUE THREAD

**Issue by gbalabasquer** [dapphub/dapptools#198]
When a test fails in an `assertEq` statement, if the values are very large, they will be rounded returning errors like this:
```
"Error: Wrong `uint' value"
    Expected: ~5.25000000e19
      Actual: ~5.25000000e19
```

It would be nice that no rounding is applied so we can get accurate results.

**Comment by gbalabasquer** [comment]
Right now the only way to see the difference is with `-v` and looking at the log trace.

**Comment by asymmetric** [comment]
@rainbreak this probably touches hevm, right?

**Comment by livnev** [comment]
@gbalabasquer @rain tbh I'm not seeing any reason to use scientific notation when displaying EVM words in this case. Can I just change it to just print the entire word? Like 60% of the time when I am using this feature I am actually debugging a rounding issue so it seems better that way.

**Comment by rainbreak** [comment]
@livnev you mean the entire word as a uint, right?

**Comment by livnev** [comment]
> @livnev you mean the entire word as a uint, right?

@rain yes, in the case that the type is a `uint*` print the entire word as a `uint`.

**Comment by rainbreak** [comment]
```
"Error: Wrong `uint' value"
    Expected: ~1.25000000e18
      Actual: ~1.25000000e18

  "Error: Wrong `uint' value"
    Expected: 1,250,000,000,000,000,000
      Actual: 1,250,000,000,000,000,001

  "Error: Wrong `uint' value"
    Expected: 1250000000000000000
      Actual: 1250000000000000001
```

@livnev @gbalabasquer you both want version 3, right?

**Comment by gbalabasquer** [comment]
@rainbreak yeah version 3 would be the best
