### ISSUE TITLE
Pass relevant subset of Ethereum VM test suite

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#2]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Wednesday Sep 06, 2017 at 13:27 GMT_
_Originally opened as https://github.com/dapphub/hevm/issues/7_

----

**Comment by mbrock** [comment]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mbrock](https://github.com/mbrock)**
_Friday Sep 29, 2017 at 16:26 GMT_

----

Going to clarify this and work on it next week.

At least now we have a good test suite runner for `VMTests`.

**Comment by mbrock** [comment]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mbrock](https://github.com/mbrock)**
_Wednesday Oct 11, 2017 at 06:10 GMT_

----

As of 0.10 there are only five unexplained `VMTests` mismatches, and the rest of the 25 mismatches are explained:

  - 12 are timeouts from the `vmPerformance` suite, they probably work in fact;
  - 7 are because we don't implement `CALLCODE`; and
  - 1 is because of precompiled contracts.

The unexplained mismatches are:

  - `vmSystemOperations/ABAcalls1`
  - `vmSystemOperations/ABAcalls2`
  - `vmSystemOperations/ABAcalls3`
  - `vmTests/arith`
  - `vmTests/mktx`

These all unexpectedly succeed instead of erroring. It seems like they should fail on `CALL` instructions, but I don't know why -- and `CALL` isn't really executed in the VMTests anyway, so it's kind of strange.

**Comment by asymmetric** [comment]
Superseded by #92.
