### ISSUE TITLE
Infinite loop if libexec/seth is not available

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#20]
<a href="https://github.com/travs"><img src="https://avatars3.githubusercontent.com/u/7369273?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [travs](https://github.com/travs)**
_Monday Sep 04, 2017 at 15:27 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/51_

----

Recreate:
```
mkdir thing && cd thing
dapp init
make all
make deploy # just calls "dapp create Thing"
```

Output:
```
bash: warning: shell level (1000) too high, resetting to 1
```
(over and over)

Running:
```
linux 4.12.8-2-ARCH
zsh (inside tmux)
```

**Comment by asymmetric** [comment]
Seems like an installation error, closing, will reopen if more people hit it.
