### ISSUE TITLE
Prototype of Nix integration and solc picking

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#21]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Friday Sep 08, 2017 at 20:05 GMT_
_Originally opened as https://github.com/dapphub/dapp/pull/54_

----

This pretty much works fine! But we shouldn't merge it immediately, 
there's some stuff to consider and some stuff to do.

See #53. cc @dbrock 

I can run dapp in a clean Ubuntu Docker, and it will commence installing
Nix, setting up the DappHub Nix channel, and then reinstalling dapp
via Nix.

It's kind of weird though that you would first download the dapp source
code and install it, and then it would immediately reinstall itself in a
different place using Nix.

So I'm not sure, maybe there should be a separate easy install script,
instead of the check in the main dapp program.

Until this dapp version is actually in Nix, the `dapp --use` won't work.

----

_**[mbrock](https://github.com/mbrock)** included the following code: https://github.com/dapphub/dapp/pull/54/commits_

**Comment by asymmetric** [comment]
This is obsolete.
