### ISSUE TITLE
Automatically link libraries when calling "dapp build"

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#22]
<a href="https://github.com/travs"><img src="https://avatars3.githubusercontent.com/u/7369273?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [travs](https://github.com/travs)**
_Tuesday Sep 19, 2017 at 13:48 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/55_

----

Right now, libs need to be linked manually (i.e. with `solc`).
One alternative would be to link automatically on `solc build` unless some addresses are supplied (idea from @rainbreak)

**Comment by rainbreak** [comment]
This was done and should work with `dapp test`.
