### ISSUE TITLE
Hevm: jump to end exits hevm

### ISSUE THREAD

**Issue by lucasvo** [dapphub/dapptools#221]
jumping to end in a test results in hevm exiting with the following output:

```
hevm: VM error: VMFailed (Revert "")
CallStack (from HasCallStack):
error, called at src/EVM/TTY.hs:238:11 in hevm-0.31-KIqqGtEfcBA8HDPWSpQyph:EVM.TTY
```

The following code can be used to reproduce it: https://github.com/centrifuge/tinlake/tree/ac5cb5b2ecdcd946ee6669534789a704b6998ad6 << `dapp debug out/test/deployer.t.sol.json` - SystemTest::testBorrowAndRepay()

**Comment by livnev** [comment]
More generally what happens is that `hevm interactive` still exits when it reaches any VM failure, the recent change that made it stop at the end only works for executions that end "successfully".
