### ISSUE TITLE
hevm: weird failure on test case

### ISSUE THREAD

**Issue by gbalabasquer** [dapphub/dapptools#222]
Testing `ds-auth` with at the latest `dapp/hevm` version (0.31) it is returning a failure case for `test_accepting_authority` and a succeed for the `fail` cases (however not due their failure logic but about an out of gas issue).

Removing this unused line `BooleanAuthority rejector = new BooleanAuthority(false);` fixes the failure, which clearly doesn't make sense.

**Comment by livnev** [comment]
@gbalabasquer This looks weird indeed, and must be due to some recent semantic changes I introduced while fixing bugs in the `GeneralStateTests`. I'll try to determine whether or not this is correct behaviour (probably not). I'm on holiday at the moment so it might take a while.

**Comment by gbalabasquer** [comment]
Thanks @livnev. We can wait for this fix, enjoy your holiday!
Btw I think @icetan was closed to find the commit that introduced this change of behavior.

**Comment by gbalabasquer** [comment]
Thanks @livnev !
