### ISSUE TITLE
missing or bad C library while building hevm 0.31

### ISSUE THREAD

**Issue by johnsoncarl** [dapphub/dapptools#223]
I was trying to build a tool though `stack install`.
The build seems to be failing sure to missing `ff` library in C.
I cannot find any solution to this.
I have tried almost everything to solve this, what could be the exact solution exactly for this?

```
Configuring hevm-0.31...
    Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: Missing dependency on a foreign
    library:
    * Missing (or bad) C library: ff
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
    library file does exist, it may contain errors that are caught by the C
    compiler at the preprocessing stage. In this case you can re-run configure
    with the verbosity flag -v3 to see the error messages.
```

**Comment by rainbreak** [comment]
Do you have libff installed somewhere?

**Comment by livnev** [comment]
@johnsoncarl note that installing with `stack` is not our recommended method: the preferred way is to use `nix`. If you prefer to use `stack` then you'll need to build and globally install `scipr/libff` somehow.

**Comment by johnsoncarl** [comment]
@rainbreak @livnev I have tried installing libff but nothing seems to work.

Could you please tell some different method to install it?

@livnev I am installing another application https://github.com/crytic/echidna which depends on `hevm`.

**Comment by johnsoncarl** [comment]
okay, installed `libff` successfully. 


But the same problem persists. I am unable to install the tool.

**Comment by gbalabasquer** [comment]
@johnsoncarl the easiest way to install `hevm` is using the instructions of https://dapp.tools/ (via nix).
`curl https://dapp.tools/install | sh` should do all the trick (make sure to restart the terminal after the installer ends).
I think the only problem you might have if you had already installed a nix version prev to 2.0, otherwise everything should run smoothly.

**Comment by johnsoncarl** [comment]
> @rainbreak @livnev I have tried installing libff but nothing seems to work.
> 
> Could you please tell some different method to install it?
> 
> @livnev I am installing another application https://github.com/crytic/echidna which depends on `hevm`.

Hey @gbalabasquer , I was installing this tool. So I may not have any option to install `hevm` via `nix`.

So, could you suggest something else.

Though I've opened an issue in echidna regarding this. But you could help if it is `hevm` problem

**Comment by livnev** [comment]
@johnsoncarl Looks like you managed to install `echidna` and closed the issue, so I'm going to close this one as well. Let us know if you need help.
