### ISSUE TITLE
package doesn't exist

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#23]
<a href="https://github.com/et"><img src="https://avatars3.githubusercontent.com/u/58678?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [et](https://github.com/et)**
_Friday Sep 22, 2017 at 04:48 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/57_

----

In the [docs](https://github.com/dapphub/dapp/blame/e24b31b28396eba9c8d6da7715d6a8debfd50c27/docs/package_management.rst#L32), it says to install `dapp install apmilen/my-cool-package`. However, that repo does not exist.

**Comment by mbrock** [comment]
<a href="https://github.com/nmushegian"><img src="https://avatars0.githubusercontent.com/u/924397?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nmushegian](https://github.com/nmushegian)**
_Friday Sep 22, 2017 at 17:20 GMT_

----

Ah I just read the context.. we'll rewrite for clarity

**Comment by asymmetric** [comment]
Not relevant anymore.
