### ISSUE TITLE
Renounce impurity

### ISSUE THREAD

**Issue by asymmetric** [dapphub/dapptools#232]
`dapp pkg` [currently](
https://github.com/dapphub/dapptools/tree/e3e0e843f7b1403d1c934eb3feafc61cc91653c2/src/dapp/libexec/dapp/dapp-pkg#L38-L43) `cd`'s into `$DAPPTOOLS` and runs a bunch of impure operations (`git pull`, `nix-env`).

This has several drawbacks:

* the system is less declarative
* the abstraction is leaky (`git pull` might fail to merge)
* ...

The better(tm) way to do this is to `import` dapptools and declare the list of packages that should be available, either in a system-wide `configuration.nix` or within something like Home Manager.

The drawback here is that a novice user will have to actually learn how Nix works. Whether this is an actual drawback is unclear.

**Comment by asymmetric** [comment]
This would also allow us to completely remove `~/.dapp`, closing #123.

**Comment by MrChico** [comment]
@asymmetric impurity renounced by #377 ?

**Comment by asymmetric** [comment]
Yep.
