### ISSUE TITLE
`seth balance` returns 0 when address is without 0x prefix

### ISSUE THREAD

**Issue by liamzebedee** [dapphub/dapptools#235]
Love your tooling, although the encoding has confused me a bit at times. Is this issue considered worth fixing?

**Comment by livnev** [comment]
Hmm, I get `seth-rpc: error:   message    Invalid params: expected a hex-encoded hash with 0x prefix.` when I give `seth balance` an address without the `0x` prefix. Are you on the latest `dapptools`? Try `dapp pkg selfupdate`.
