### ISSUE TITLE
Kernel freeze on OS X High Sierra (Nix)

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#24]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Friday Oct 20, 2017 at 18:42 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/61_

----

Sadly, Nix breaks the kernel on High Sierra, because of a bug Apple introduced and will hopefully fix.

This results in freezes and kernel panics when installing Nix packages!

The workaround is to use Nix in "single user mode" rather than using the Nix daemon.

Here's how to switch, after you've installed Nix:

```
sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
sudo launchctl stop org.nixos.nix-daemon
sudo chown -R $(whoami) /nix
sudo sed -i /build-users-group/d /etc/nix/nix.conf
echo "export NIX_REMOTE=" >> ~/.bashrc
```

After that, the Nix commands should work again.

**Comment by rainbreak** [comment]
I think this was resolved.
