### ISSUE TITLE
dapp create doesn't recognize the new dapp.sol.json file

### ISSUE THREAD

**Issue by gbalabasquer** [dapphub/dapptools#244]
We've missed to adapt this command.

**Comment by rainbreak** [comment]
Should work if `dapp build --extract` is used, but yes this is broken otherwise.

**Comment by rainbreak** [comment]
To get this from the json we need to index by the full filepath, e.g. 

```
<out/dapp.sol.json jq '.contracts["src/math.sol:DSMath"].bin' -r
```

The caller could provide the fully qualified name with the filepath (useful in case of collisions), or they can provide just the contract name as before, and we select the first instance of it in the json.

**Comment by gbalabasquer** [comment]
Right, it works with `--extract`, but I guess we want to bring the value directly from the `dapp.sol.json` so it works always.

I think that is the best solution, to have both options, full path to avoid collisions, and first instance if not specified.

**Comment by nanexcool** [comment]
https://github.com/dapphub/dapptools/pull/351 fixes this :)

**Comment by asymmetric** [comment]
@gbalabasquer let us know if this fixes your issue and then we can close this :)

**Comment by gbalabasquer** [comment]
Yes, thanks!
