### ISSUE TITLE
hevm: some MODEXP calls fail with libc++abi.dylib: terminating with uncaught exception of type int

### ISSUE THREAD

**Issue by MrChico** [dapphub/dapptools#248]
Running any code that triggers the `modexp` precompile leads to:
```
hevm bc-test --file ~/dapphub/klab/evm-semantics/tests/ethereum-tests/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json
create2callPrecompiles_d5g0v0_ConstantinopleFix libc++abi.dylib: terminating with uncaught exception of type int
[1]    83906 abort      hevm bc-test --file
```

**Comment by livnev** [comment]
@MrChico Does invoking `expFast` from the repl also lead to this crash?

**Comment by MrChico** [comment]
No, it seems to work just fine

**Comment by livnev** [comment]
in that case I think it's the same OOM issue for `expFast` with large numbers, which we are already aware of. Closing.

**Comment by MrChico** [comment]
Could be I'm not sure

**Comment by livnev** [comment]
Actually this seems like it might be a separate issue, on my machine the same test doesn't crash:

```
[nix-shell:~/dapps/dapptools/src/hevm]$ $HEVM bc-test --file ~/dapps/ethereum/tests/BlockchainTests/GeneralStateTests/stCreate2/create2callPrecompiles_d5g0v0.json
create2callPrecompiles_d5g0v0_ConstantinopleFix bad-balance
```

**Comment by desaperados** [comment]
I can reproduce this issue on my Mac: 293no. `libc++abi.dylib: terminating with uncaught exception of type int` failures, including the example posted here and the contents of `BlockchainTests/GeneralStateTests/stZeroKnowledge2`.

```
9766 passed, 
0 bad-balance, 
293 failed, 
0 skipped
```

Whereas the same tests pass on my NixOS machine.

**Comment by rainbreak** [comment]
Wondering if this could be a clang vs gcc issue.

**Comment by desaperados** [comment]
This fix takes care of the exceptions on darwin - matching the linux output now except for a single bad-nonce fail. 

<img width="792" alt="Screen Shot 2019-08-07 at 8 50 43 PM" src="https://user-images.githubusercontent.com/5028/62608997-10662880-b955-11e9-9fee-7c8f041b0205.png">
