### ISSUE TITLE
the --rpc flag in hevm interactive

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#257]
From what I can tell, RPC fetching doesn't currently work in `hevm interactive`. For example, using [this dapp](https://github.com/makerdao/mkr-authority/tree/hevm) and running

```
dapp build && DAPP_TEST_TIMESTAMP=$(seth block latest timestamp) DAPP_TEST_NUMBER=$(seth block latest number) DAPP_TEST_ADDRESS=0x8EE7D9235e01e6B42345120b5d270bdB763624C7 hevm dapp-test --rpc=$ETH_RPC_URL --json-file=out/dapp.sol.json
```

sees all tests pass (as you would expect if the state is being fetched), however replacing `dapp-test` with `interactive` and inspecting `testChangeOwners()` makes the test fail, and the cause of the failure is an attempted call into a non-existent contract, so it looks like the fetcher is not working in this case. A cursory examination of `hevm-cli.hs` and `Fetch.hs` didn't turn up an obvious reason why the RPC isn't being called.

cc @rainbreak

**Comment by livnev** [comment]
FYI `Fetch.hs` uses (the IMO annoying 😆 ) `ImplicitParams` language extension which enables dynamic binding, the `fetcher` is bound dynamically throughouit.

**Comment by rainbreak** [comment]
@desaperados is looking at this atm

**Comment by livnev** [comment]
Can confirm that #262 fixes this test case, but noticed that it is still broken with `hevm dapp-test --debug`...

**Comment by desaperados** [comment]
#262 should fix all cases - how is it broken with `dapp-test --debug`?

**Comment by livnev** [comment]
> #262 should fix all cases - how is it broken with `dapp-test --debug`?

Whoops, I am unable to reproduce that issue so I think it was because I hadn't set `DAPP_TEST_TIMESTAMP` or something.

**Comment by desaperados** [comment]
Ah could be. It's easy to forget to specify a block number which always results in a fail. I've changed the defailt to `latest` to avoid this.
