### ISSUE TITLE
hevm: Istanbul compatibility

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#258]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1679.md

Also time to reconsider whether or not `hevm` should support configuring the network regime.

also cf. https://github.com/kframework/evm-semantics/issues/442

**Comment by MrChico** [comment]
this could be useful for blake2
https://github.com/runtimeverification/blockchain-k-plugin/blob/master/plugin-c/blake2.cpp

**Comment by MrChico** [comment]
Closed via #318
