### ISSUE TITLE
Change Dockerfile to use Nix

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#26]
<a href="https://github.com/dbrock"><img src="https://avatars1.githubusercontent.com/u/14032?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbrock](https://github.com/dbrock)**
_Monday Dec 11, 2017 at 09:18 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/69_

----

Instead of https://github.com/dapphub/dapp/pull/64

**Comment by asymmetric** [comment]
Closed because of #422?

**Comment by MrChico** [comment]
this was closed because everything have been nixified
