### ISSUE TITLE
msg.sender is zero address on hevm version .34

### ISSUE THREAD

**Issue by realisation** [dapphub/dapptools#268]
Simple test shows that msg.sender is the zero address: 

```
pragma solidity ^0.5.6;

import "ds-test/test.sol";

contract DappTest is DSTest {
    event logMsgSender(bytes32,  address);

    function setUp() public {
        emit logMsgSender("msg.sender", msg.sender);
    }

    function testMsgSender() public {
        bool equals0 = msg.sender == address(0);
        assertTrue(!equals0);
    }

}
```

**Comment by livnev** [comment]
This appears to be a bug: `msg.sender` should default to `ethrunAddress = Addr 0x00a329c0648769a73afac7f9381e08fb43dbea72` and should be overrideable with `DAPP_TEST_CALLER`, but this does not seem to be the case.

**Comment by desaperados** [comment]
The test options are being passed and `caller` gets set to the correct initial value - but it's then being zeroed when `setupCall` resets the state: https://github.com/dapphub/dapptools/blob/master/src/hevm/src/EVM/UnitTest.hs#L533
