### ISSUE TITLE
NixOS install broken on Mac OS Catalina

### ISSUE THREAD

**Issue by sethfork** [dapphub/dapptools#285]
This affects the dapptools install script, as well as the install script from nixos.

See https://github.com/NixOS/nix/issues/2925

**Comment by manuelpolzhofer** [comment]
I upgraded to MacOS Catalina and fixed dapptools by creating a APFS volume for nix as a workaround.

described here by @callahad 
https://github.com/NixOS/nix/issues/2925#issuecomment-539570232

I followed step 1 and step 2 and afterwards just copied my existing nix folder (new path in Catalina) to `/nix`
```
sudo chown -R $(whoami) /nix
cp -a /Users/Shared/Relocated\ Items/Security/nix/* /nix/
```
(nix copy in `/Users/Shared/...` can be removed afterwards)

After that: `dapp` worked again.
