### ISSUE TITLE
hevm: support json trace

### ISSUE THREAD

**Issue by MrChico** [dapphub/dapptools#288]
`geth`, `parity` and `aleth` and others support a traced output in json format. The details differ... Here is geth:
```
{"pc":0,"op":96,"gas":"0x2540be400","gasCost":"0x0","memory":"0x","memSize":0,"stack":[],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":2,"op":96,"gas":"0x2540be3fd","gasCost":"0x0","memory":"0x","memSize":0,"stack":["0x80"],"depth":1,"refund":0,"opName":"PUSH1","error":""}
{"pc":4,"op":82,"gas":"0x2540be3fa","gasCost":"0xc","memory":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","memSize":96,"stack":["0x80","0x40"],"depth":1,"refund":0,"opName":"MSTORE","error":""}
{"pc":5,"op":52,"gas":"0x2540be3ee","gasCost":"0xc","memory":"0x000000000000000000000000000000000000000000000000000000000
```
`aleth`:
```
{"pc": 0, "gas": "0x7fffffffffffffff", "gasCost": "0x3", "stack": [], "depth": 0, "opName": "PUSH1"}
{"pc": 2, "gas": "0x7ffffffffffffffc", "gasCost": "0x3", "stack": ['0x80'], "depth": 0, "opName": "PUSH1"}
{"pc": 4, "gas": "0x7ffffffffffffff9", "gasCost": "0x3", "stack": ['0x80', '0x40'], "depth": 0, "opName": "MSTORE"}
{"pc": 5, "gas": "0x7fffffffffffffed", "gasCost": "0x2", "stack": [], "depth": 0, "opName": "CALLVALUE"}
{"pc": 6, "gas": "0x7fffffffffffffeb", "gasCost": "0x3", "stack": ['0x00'], "depth": 0, "opName": "DUP1"}
```

See more discussion here:
https://github.com/ethereum/tests/issues/249

This would be helpful for more testing of hevm, including random testing against other implementations

**Comment by gumb0** [comment]
We plan to change the format to closer match geth https://github.com/ethereum/aleth/issues/5804

**Comment by livnev** [comment]
Would also be cool to support some [parity tracing features](https://wiki.parity.io/JSONRPC-trace-module).

**Comment by MrChico** [comment]
Another possible thing that this could lead to is to make the (still hypothetical) `seth debug 0xtxhash` available to the browser

**Comment by livnev** [comment]
> Another possible thing that this could lead to is to make the (still hypothetical) `seth debug 0xtxhash` available to the browser

What do you have in mind exactly?

**Comment by MrChico** [comment]
Generate a proof trace, and make a clicky version of `replay this transaction`. Would need to involve some saas stuff. Just spitballin here
