### ISSUE TITLE
Memory leak in hevm when running a tight loop

### ISSUE THREAD

**Issue by ggrieco-tob** [dapphub/dapptools#296]
Executing a contract with a tight loop make `hevm` to allocate an unbounded amount of memory (e.g. taking around 10 GB in less than a minute). To reproduce, create a new dapp project like this one:

```
$ cat src/Dapp.sol 
pragma solidity ^0.4.25;

contract Dapp {
}
$ cat src/Dapp.t.sol 
pragma solidity ^0.4.25;

import "ds-test/test.sol";

import "./Dapp.sol";

contract DappTest is DSTest {
    Dapp dapp;

    function setUp() public {
        dapp = new Dapp();
    }

    function testFail_basic_sanity() public {
        for(uint i = 0; i <= 2**128; i++) {}
        assertTrue(false);
    }

    function test_basic_sanity() public {
        assertTrue(true);
    }
}
```

and run `dapp test`. Then, you can watch the memory consumption grow (e.g. using `top` in Linux)

**Comment by MrChico** [comment]
Hmm, I'm not able to reproduce this behaviour on MacOS. Memory stays constant around 5032K

**Comment by rainbreak** [comment]
@ggrieco-tob could you give more details about your setup?

**Comment by ggrieco-tob** [comment]
Sorry for the delay. The issue was tested in Linux (e.g. Ubuntu 18.04), so you can test it either with docker or vagrant in MacOS. It is also interesting to note that the code executed will not fail for an out-of-gas revert, despite will consume large amounts of it.

**Comment by livnev** [comment]
> Sorry for the delay. The issue was tested in Linux (e.g. Ubuntu 18.04), so you can test it either with docker or vagrant in MacOS. It is also interesting to note that the code executed will not fail for an out-of-gas revert, despite will consume large amounts of it.

I was not able to reproduce this on Linux with nixOS. Could you please provide a more detailed reproduction recipe?

By the way, the default starting gas for a test invocation is `2^48 - 1`, if you want to use something more realistic you can do `DAPP_TEST_GAS_CALL=10000000 dapp test`, then the test will end pretty quickly.

**Comment by ggrieco-tob** [comment]
> @ggrieco-tob I was not able to reproduce this on Linux with nixOS. Could you please provide a more detailed reproduction recipe?

I used `stack` to build `hevm`. I don't know if that makes any difference, which version of ghc is used in NixOS to build hevm? 

I can try to reproduce this in a vagrant box and paste here the recipe for that. 

> By the way, the default starting gas for a test invocation is 2^48 - 1, if you want to use something more realistic you can do DAPP_TEST_GAS_CALL=10000000 dapp test, then the test will end pretty quickly.

At least, that works :smile: .

**Comment by livnev** [comment]
@ggrieco-tob I believe it uses `ghc` 8.6.5. Please let us know if that changes things for you.

**Comment by ggrieco-tob** [comment]
Upgrading to 8.9.5 fixes the memory leak! :tada:  

However, now hevm consumes 100% of all my CPUs to execute a single test (when running `dapp test`). Is that expected? Can you reproduce this with the example I'm providing?

**Comment by livnev** [comment]
@ggrieco-tob I did manage to get a load of `4.99` on a machine with 12 cores. I don't know why it's doing that, to be honest, but I don't think it is a huge issue?

**Comment by ggrieco-tob** [comment]
It is not a big issue, let's close this and open later a new one to investigate the use of multiple cores. Thanks and sorry for all the trouble.
