### ISSUE TITLE
'dapp test' uses 0 for 'now'

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#31]
<a href="https://github.com/wjmelements"><img src="https://avatars1.githubusercontent.com/u/799573?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wjmelements](https://github.com/wjmelements)**
_Friday Feb 16, 2018 at 12:54 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/77_

----

Ideally, the testing environment can let me set the current value of now, such as:

```
contract Test is DSTest {
  function test_now() {
     uint uptime = subject.getUptime();
     now += 2000;
     assertEq(uptime + 2000, subject.getUptime());
  }
}
```

But critically, nothing time-related can be unit tested at the moment. Simply defaulting now to the current time instead of '0' or '1' would be a huge benefit for me.

Thanks

**Comment by mbrock** [comment]
<a href="https://github.com/wjmelements"><img src="https://avatars1.githubusercontent.com/u/799573?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wjmelements](https://github.com/wjmelements)**
_Friday Feb 16, 2018 at 19:31 GMT_

----

This looks like the prescribed solution: https://github.com/dapphub/ds-warp

**Comment by mbrock** [comment]
<a href="https://github.com/wjmelements"><img src="https://avatars1.githubusercontent.com/u/799573?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [wjmelements](https://github.com/wjmelements)**
_Friday Feb 16, 2018 at 19:45 GMT_

----

https://github.com/dapphub/ds-warp/issues/2

**Comment by rainbreak** [comment]
time related things:

- control the initial timestamp with `DAPP_TEST_TIMESTAMP` environment variable
- implement a `time()` method that returns the block timestamp, and then override that in a test contract
- call `warp` on the hevm cheat address (undocumented new feature since 0.19)
