### ISSUE TITLE
`dapp build` library linking is broken

### ISSUE THREAD

**Issue by MrChico** [dapphub/dapptools#310]

**Comment by MrChico** [comment]
There seems to be a couple of things at play here. There's obvious errors in that `dapp --make-library-state` assumes that the libraries binaries are available (which they would be in case of `dapp build --extract`, but even with a proper library binary set up, I'm not able to get the restless Git to load the preloaded state...

**Comment by livnev** [comment]
Do we need to support this? Is there a recorded instance of anyone every using this?

**Comment by MrChico** [comment]
Not necessarily, but there seems to be a whole lot of scaffolding around it already, and if we aren't planning on supporting it we should probably deprecate that

**Comment by MrChico** [comment]
I guess what's more interesting to me is to find out why the restless git stuff doesn't work as intended

**Comment by MrChico** [comment]
This might be fake news. Things are working fine for the uniswap build for example. I think the real issue is I still havent figured out how hevm deals with state but thats another story.
