### ISSUE TITLE
Package seth to non-NixOs

### ISSUE THREAD

**Issue by louptheron** [dapphub/dapptools#311]
Hi, 
When I package `seth` to a NixOs based docker image, the image is quite big (5.7GB) ; here's the Dockerfile:
```shell
FROM alpine:latest

RUN adduser -D sethservice && \
    mkdir -m 0755 /nix && chown sethservice /nix && \
    mkdir -p /etc/nix && echo 'sandbox = false' > /etc/nix/nix.conf && \
    apk --no-cache add ca-certificates curl git

USER sethservice
RUN curl https://nixos.org/nix/install | sh && source $HOME/.nix-profile/etc/profile.d/nix.sh && \
    echo "export PATH=$PATH:$HOME/.nix-profile/bin" >> $HOME/.profile && \
    source $HOME/.profile && \
    git clone --recursive https://github.com/dapphub/dapptools $HOME/.dapp/dapptools && \
    nix-env -f $HOME/.dapp/dapptools -iA seth

# Checking if seth is there
RUN source $HOME/.profile && which seth
```

So I would like to package`seth` as a binary to use it on a `alpine` based docker image (i.e with a multistage docker build), it is possible ? Any idea how I could achieve that ?

Thank you

**Comment by xwvvvvwx** [comment]
@louptheron I'm not sure if this is exactly what you wanted, but I was able to produce a 119M docker image using the following `nix` derivation:

```nix
let

  pkgs = import (builtins.fetchGit rec {
    name = "nixos-unstable-${ref}";
    url = https://github.com/nixos/nixpkgs/;
    ref = "nixos-19.09";
  }) {};

  dapptools = import (builtins.fetchGit rec {
    name = "dapptools-${rev}";
    url = https://github.com/dapphub/dapptools;
    rev = "3e62bd54dfbc23b76d9234f94a7387504b360d5d";
    ref = "dapp/0.25.0";
  }) {};

in pkgs.dockerTools.buildImage {
  name = "seth";
  tag = "latest";

  contents = dapptools.seth;
  config.Cmd = [ "/bin/seth" ];
}
```

You can build the image using `nix build -f <PATH_TO_DERIVATION>`, and then load the resulting image using `docker load --input <PATH_TO_IMAGE>.

**Comment by louptheron** [comment]
Thank you very much @xwvvvvwx for giving me this example and pointers !
I would now be able to include my service along `seth` (I'm new in the Nix world).
