### ISSUE TITLE
Unable to install alternative solc

### ISSUE THREAD

**Issue by travs** [dapphub/dapptools#312]
I want to install an older version of `solc` than the one that comes by default (when I install everything with the script at `https://dapp.tools/install`).

```
$ uname -ro 
4.19.87-1-lts GNU/Linux

$ nix --version
nix (Nix) 2.3.1
```

This is what I try and where it fails.

```
$ nix-env -v=5 -f $HOME/.dapp/dapptools -iA solc-versions.solc_0_4_25

evaluating file '/nix/store/6chjfy4j6hjwj5f8zcbbdg02i21x1qsi-nix-2.3.1/share/nix/corepkgs/derivation.nix'
evaluating file '/home/travis/.dapp/dapptools/default.nix'
using revision f1707d8875276cfa110139435a7e8998b4c2a4fd of repo 'https://github.com/nixos/nixpkgs'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/minver.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/impure.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/booter.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/fixed-points.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/lists.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/systems/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/attrsets.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/systems/inspect.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/trivial.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/systems/parse.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/strings.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/types.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/options.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/systems/platforms.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/linux/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/stage.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/adapters.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/build-support/trivial-builders.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/splice.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/all-packages.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/top-level/aliases.nix'
evaluating file '/home/travis/.dapp/dapptools/overlay.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/generic/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/lib/customisation.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/tools/text/gawk/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/servers/x11/xorg/default.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/servers/x11/xorg/overrides.nix'
evaluating file '/nix/store/yjn9wrqqp3ajndhh59vw5v8hisljkf9b-source/pkgs/stdenv/generic/make-derivation.nix'
error: attribute '=5' in selection path '=5' not found
```

**Comment by livnev** [comment]
@travs you were close, not sure where `-v=5` came from but this works (at least on my machine):

`$ nix-env -f $HOME/.dapp/dapptools -iA solc-versions.solc_0_4_25`

Also FYI, here's a one-liner when you want to execute a command using a specific version of `solc`, useful when you want to write a script that uses a specific `solc` version without changing the one in your path:

```
$ dapp --nix-run solc-versions.solc_0_4_25 solc --version
```

**Comment by travs** [comment]
@livnev Oh wow, gotta be kidding me. :man_facepalming: It was my failed attempt at getting more verbosity since the installation was taking forever (due to an unrelated network issue).

Works now that my internet's back on. Thanks!

**Comment by PaulRBerg** [comment]
I have a similar use case, where I want to install a different version of `solc` than the one that `dapptools` comes bundled with (0.5.15).

I moved my nix loader script before all other commands in `.bash_profile`, but the nix solc still takes precedence over homebrew.

I think this is a scenario common enough to be worthy to be mentioned in the README/ docs.

**Comment by livnev** [comment]
> I have a similar use case, where I want to install a different version of `solc` than the one that `dapptools` comes bundled with (0.5.15).
> 
> I moved my nix loader script before all other commands in `.bash_profile`, but the nix solc still takes precedence over homebrew.
> 
> I think this is a scenario common enough to be worthy to be mentioned in the README/ docs.

Can you elaborate on what you are trying to do? Have you tried using commands like `dapp --use solc:0.4.25` or `dapp --nix-run solc-versions.solc_0_4_25 solc --version` ?

**Comment by PaulRBerg** [comment]
I was trying to compile some contracts with the `solc` executable from homebrew.

I didn't run the commands you mentioned, but the "lock-in" effect of nix overriding most of my tools is a showstopper. It's a shame, as `seth` has many useful scripts.

**Comment by livnev** [comment]
> I was trying to compile some contracts with the `solc` executable from homebrew.
> 
> I didn't run the commands you mentioned, but the "lock-in" effect of nix overriding most of my tools is a showstopper. It's a shame, as `seth` has many useful scripts.

@PaulRBerg I believe this needn't be a problem. If you don't want to have the `dapptools` provided `solc` in your `$PATH`, just remove it with `nix-env -e solc`. You can also fiddle with how your `$PATH` is ordered if you want to keep it but have a different `solc` take precedence (it sounds like you already tried doing this).

**Comment by PaulRBerg** [comment]
> You can also fiddle with how your $PATH is ordered if you want to keep it but have a different sol

Already implemented this in multiple ways and none worked - I reloaded my console several times and even restarted my computer to be sure.

> `nix-env -e solc`

Exactly what I was looking for! Sorry, I am new to nix.

**Comment by livnev** [comment]
@PaulRBerg Glad that helped.

Regarding the `$PATH` precedence, I am confident it is possible to control this to do what you want. I would inspect how your `$PATH` looks (`echo $PATH`), and see what the position of `~/.nix-profile/bin` is. You want it to come later than anywhere else where you might have a `solc`.
