### ISSUE TITLE
Create .gitattributes on dapp-init

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#33]
<a href="https://github.com/nanexcool"><img src="https://avatars2.githubusercontent.com/u/52510?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nanexcool](https://github.com/nanexcool)**
_Monday Feb 26, 2018 at 18:54 GMT_
_Originally opened as https://github.com/dapphub/dapp/pull/80_

----

With this .gitattributes file, it gives a hint to Github so it correctly highlights Solidity syntax on its webpage.

----

_**[nanexcool](https://github.com/nanexcool)** included the following code: https://github.com/dapphub/dapp/pull/80/commits_

**Comment by iamchrissmith** [comment]
Would like to take this as my warm up bug

**Comment by iamchrissmith** [comment]
PR for this: https://github.com/dapphub/dapptools/pull/203

**Comment by asymmetric** [comment]
Closed by #203.
