### ISSUE TITLE
seth --to-wei should default to use ether as source currency

### ISSUE THREAD

**Issue by krzkaczor** [dapphub/dapptools#347]
```sh
seth --to-wei 1
> 1
```

according to the docs it should return eth amount in wei so: `1000000000000000000` but `1` is returned

**Comment by gbalabasquer** [comment]
`seth --to-wei 1 "eth"`

**Comment by krzkaczor** [comment]
Just my 2 cents: probably a default value for last parameter shouldn't be "wei" but "eth" or whatever that actually makes sense (why would anyone want to convert wei to wei?)

**Comment by MrChico** [comment]
> Just my 2 cents: probably a default value for last parameter shouldn't be "wei" but "eth" or whatever that actually makes sense (why would anyone want to convert wei to wei?)

agree
