### ISSUE TITLE
curl: (22) The requested URL returned error: 401

### ISSUE THREAD

**Issue by PaulRBerg** [dapphub/dapptools#350]
## Description

Each time I run a command that makes a network request, like `seth age`, I get this error:

```sh
curl: (22) The requested URL returned error: 401
+ :
```

I'm not sure whether this is caused by my Internet connection, since I tried it on both my WiFi and personal hotspot.

## Environment

+ macOS 10.14.6
+ nix-env 2.2.1
+ dapp 0.25.0
+ seth-0.8.2

**Comment by PaulRBerg** [comment]
**Update**

By providing my Infura URL via "--rpc-url", I was able to make it work. But I thought that seth would automatically connect to a node if none is provided?

**Comment by PaulRBerg** [comment]
**Update 2**

I overlooked the [configuration](https://github.com/dapphub/dapptools/tree/master/src/seth#configuration) section in the README.

After dropping `ETH_RPC_URL` in my `.sethrc` file, things went well, but NOT after using the recommended approach via `SETH_CHAIN`. With the latter, I get a similar error, but with code 403:

```sh
curl: (22) The requested URL returned error: 403
+ :
```

**Comment by MrChico** [comment]
> **Update**
> 
> By providing my Infura URL via "--rpc-url", I was able to make it work. But I thought that seth would automatically connect to a node if none is provided?

Infura recently stopped responding to queries without an API key
