### ISSUE TITLE
hevm: index out of bounds

### ISSUE THREAD

**Issue by wolflo** [dapphub/dapptools#370]
If the constructor bytecode of a '*.t.sol' contract is larger than the contract's runtime bytecode, hevm fails with:
```
hevm: ./Data/Vector/Generic.hs:245 ((!)): index out of bounds ( C , R )
CallStack (from HasCallStack):
  error, called at ./Data/Vector/Internal/Check.hs:87:5 in vector-0.12.0.2-AoZ9EwUsgIW1yrOc105QXH:Data.Vector.Internal.Check
```
where `C` is `len(constructor_bytecode) - 2` and R is `len(runtime_bytecode)`.

This only happens when the call trace is evaluated (i.e. `hevm interactive`, `dapp test -vv`, or `dapp test -v` with a failing test), and only on the unit test contract itself.

Presumably `pushTrace` is indexing the runtime code with the program counter from the `return` operation in the constructor. But I'm not sure what the fix is, or if it even needs to be fixed.

Here's a minimal contract that reproduces it:
```
pragma solidity ^0.6.0;

import "ds-test/test.sol";

contract BigConstructor is DSTest {
    bytes internal bar = hex'ff';

    function setUp() public {}
    function test() public {}
}
```
and a [script](https://github.com/wolflo/hevm-big-constructor/blob/master/bin/bc-split) that prints the bytecode size breakdown if it's helpful.

**Comment by wolflo** [comment]
I should clarify: the tests still run, it's just the trace that fails. 

If you're running `hevm interactive`, it fails anytime after the test contract constructor returns if you switch back to the trace view.

**Comment by MrChico** [comment]
Thanks for reporting @wolflo . There was indeed a problem with `pushTrace`. Please try https://github.com/dapphub/dapptools/pull/371 and see if this resolves your issue.

**Comment by wolflo** [comment]
Working for me. Thanks @MrChico
