### ISSUE TITLE
Installation fails for recurring users: installation script does not update dapptools repo

### ISSUE THREAD

**Issue by cburgdorf** [dapphub/dapptools#375]
### What is wrong

The installation via the following command fails:

`$ curl https://dapp.tools/install | sh`

#### Output

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2868  100  2868    0     0   8170      0 --:--:-- --:--:-- --:--:--  8170
remote: Repository not found.
fatal: repository 'https://github.com/makerdao/mcd-cli/' not found
Unable to fetch in submodule path 'submodules/mcd-cli'
```

**Comment by MrChico** [comment]
Looks like this repo was recently made private. These submodules should be removed. Thanks for reportinh

**Comment by MrChico** [comment]
Actually, `mcd-cli` should have been removed in #355 ... I'm not quite sure why you would end up fetching that repo

**Comment by MrChico** [comment]
@cburgdorf could you try updating the dapptools directory (possible located at your  `$HOME/.dapp/dapptools`) by a simple `git pull origin master` and installing by `nix-env -f . -iA dapp seth solc hevm ethsign` running in that same directory?

**Comment by cburgdorf** [comment]
@MrChico Thanks! That worked :+1:

**Comment by MrChico** [comment]
We should make sure to update dapptools if it already exists in the user directory when installing
