### ISSUE TITLE
dapptools installer should not install Nix by default

### ISSUE THREAD

**Issue by ehildenb** [dapphub/dapptools#376]
On a system that I already had Nix installed on, the dapptools installer (via the `curl` command in the README) installs Nix by default, and removed my existing Nix install.

This is problematic for several reasons:

-   The dapptools installer requires `sudo` access by default because the nix installation path it uses requires `sudo` access.
-   The user may already have Nix installed and likely wants to just use that existing install of Nix.

I see that there is a "manual" install available, but I think this should be the default behavior of the installer.

At the very least, the installer can be given a parameter `--no-nix-install` or something, so that the user can do something like `curl https://dapp.tools/install | bash -s -- --no-nix-install`.

**Comment by nanexcool** [comment]
That's weird, the installer checks:

- If you have Nix v1, it fails https://github.com/dapphub/dapp-tools/blob/master/install#L38
- If you have Nix v2 it shouldn't try to reinstall https://github.com/dapphub/dapp-tools/blob/master/install#L48

Maybe the way it handles checking for Nix is incomplete?

**Comment by ehildenb** [comment]
Using this `Dockerfile` (which installs Nix then dapptools):

```
FROM ubuntu:bionic

RUN    apt-get update        \
    && apt-get upgrade --yes \
    && apt-get install --yes \
        build-essential      \
        curl                 \
        git                  \
        sudo

ARG USER_ID=1000
ARG GROUP_ID=1000
RUN    groupadd -g $GROUP_ID user                             \
    && useradd -m -u $USER_ID -s /bin/sh -g user -G sudo user \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user:user
ENV USER=user
WORKDIR /home/user

RUN curl https://nixos.org/nix/install | sh
RUN curl https://dapp.tools/install    | sh
```

you get the output that I've attached: 
[docker-build-out.txt](https://github.com/dapphub/dapptools/files/4681700/docker-build-out.txt)

The dapp-tools install starts on line 807. On line 821 you can see it replaces the old Nix installation.

But really, the dapptools installer shouldn't even do any auto-detection of Nix install. It should just check if the required Nix version is installed, and fail if it isn't. Then the instructions for installing DappTools should just read:

```
curl https://nixos.org/nix/install | sh
curl https://dapp.tools/install    | sh
```

The Nix installation has many configuration options that you're not allowing the user to access otherwise. I think this approach is more in keeping with the Unix philosophy too (dapp tools installer should just install dapp tools, not Nix).

**Comment by nanexcool** [comment]
Ah, I see the problem now... Since you just installed it, `nix` isn't in the path, and the installer thinks you don't have it.
But I agree that the installer shouldn't be the one doing the nix install.

**Comment by asymmetric** [comment]
With @MrChico we were talking about removing the submodules from dapptools (because they're too Maker-specific), and at that point installing would be:

 ```
nix-env -if https://github.com/dapphub/dapptools/tarball/master --substituters https://dapp.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
```

We could slap that in the README and get rid of the install script.

There are more declarative ways (either in HM or `configuration.nix`), but those are idiomatic enough that they might not need to be mentioned explicitly.

**Comment by nanexcool** [comment]
In the meantime, I removed installing Nix from the installer

https://github.com/dapphub/dapp-tools/pull/15
