### ISSUE TITLE
seth estimate -B parameter is hex

### ISSUE THREAD

**Issue by ksvirsky** [dapphub/dapptools#387]
It is a little confusing having to pass block number as hex in seth estimate, but as dec in seth call:

seth estimate -B 0xabcdef $CONTRACT $METHOD
seth call -B 123456 $CONTRACT $METHOD

It would be great to add decimal block number support to seth estimate.
Seems like just adding the following line from seth-call to seth-estimate is enough:
[seth-call#L26](https://github.com/dapphub/dapptools/blob/ba3dfbe1969203c1435ff4b56feff79fc7253239/src/seth/libexec/seth/seth-call#L26)
[[ $ETH_BLOCK = [0-9]* ]] && ETH_BLOCK=$(seth --to-hex "$ETH_BLOCK")

**Comment by xwvvvvwx** [comment]
@ksvirsky pull requests are very welcome :slightly_smiling_face:
