### ISSUE TITLE
`dapp test` returns `error PrecompiledContractError 2` when using `sha256`

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#39]
<a href="https://github.com/retotrinkler"><img src="https://avatars1.githubusercontent.com/u/13721565?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [retotrinkler](https://github.com/retotrinkler)**
_Sunday Jun 10, 2018 at 10:39 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/90_

----

Example Solidity
```solidity
    function test_hashedSecret() public {
        assertEq(sha256(secret), hashedSecret);
    }
```
Returns
```bash
Failure: test_hashedSecret
  
  src/Htlc.t.sol:HtlcTest
   ├╴constructor
   ├╴initialize test
   │  └╴create Htlc (src/Htlc.t.sol:31)
   └╴test_hashedSecret()
      └╴error PrecompiledContractError 2 (src/Htlc.t.sol:44)
```

**Comment by MrChico** [comment]
this is no longer an issue
