### ISSUE TITLE
Basic key generation and management commands for seth

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#392]
It would be great if it was possible to generate a private key with `seth`. This will likely introduce external dependencies, but it's worth thinking about.

**Comment by MrChico** [comment]
how about `dapp --nix-run go-ethereum geth account new`

**Comment by livnev** [comment]
🤩 wow!

I will test that and maybe propose that we wrap it with `seth account new`  or something like that?

**Comment by MrChico** [comment]
dup of #174 . I'll close for now
