### ISSUE TITLE
seth broken

### ISSUE THREAD

**Issue by bizso09** [dapphub/dapptools#393]
I'm getting on Kovan this error. What's wrong? Running MacOS Mojave

```
seth send $FAUCET "drip(address)" $DAI
```
```
hevm: (^?!): empty Fold
CallStack (from HasCallStack):
  error, called at src/Control/Lens/Fold.hs:1285:28 in lens-4.17-EvV8Ak8dyWSCCOmPpOQSqE:Control.Lens.Fold
  ^?!, called at hevm-cli/hevm-cli.hs:586:53 in main:Main
```

**Comment by MrChico** [comment]
hmmm, not able to reproduce.. 
I assume you are running `seth 0.9.0`? Is `$FAUCET` and `$DAI` well defined? What is the output of `seth abi "drip(address)"`?

**Comment by MrChico** [comment]
possibly related to #383 ?

**Comment by MrChico** [comment]
Likely user error. Closing. Reopen if the error persists
