### ISSUE TITLE
 `dapp test` sets `msg.sender == 0` which is bad for testing eth or token transfers

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#40]
<a href="https://github.com/retotrinkler"><img src="https://avatars1.githubusercontent.com/u/13721565?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [retotrinkler](https://github.com/retotrinkler)**
_Sunday Jun 10, 2018 at 10:43 GMT_
_Originally opened as https://github.com/dapphub/dapp/issues/91_

----

Example Solidity
```Solidity
        // Transfer to owner
        owner.transfer(amount);
```
where `owner == msg.sender`, dapp test sets `msg.sender == 0` which then results in a failing test:
```bash
     │  ├╴call HtlcTest::[fallback function](0x) (src/Htlc.sol:61)
      │  │  └╴error Revert (src/Htlc.t.sol:6)
      │  └╴error Revert <source not found>
      └╴error Revert <source not found>
```

`0.transfer(amount)` seems to trigger fallback function; to have a non-zero default for msg.sender could help

**Comment by rainbreak** [comment]
I think this is actually resulting from an undefined fallback function on the test contract.
