### ISSUE TITLE
Support for Diamonds

### ISSUE THREAD

**Issue by mudgen** [dapphub/dapptools#403]
It would be great if Dapp provided support for deploying and upgrading diamonds. The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2020/06/diamond-setter-ethereum-smart-contract-manager/

**Comment by asymmetric** [comment]
![foo](https://user-images.githubusercontent.com/101816/85041759-e5a24e80-b179-11ea-96c1-178b116e314c.png)

Please don't spam our repos.
