### ISSUE TITLE
Reverse condition

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#42]
<a href="https://github.com/dbrock"><img src="https://avatars1.githubusercontent.com/u/14032?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dbrock](https://github.com/dbrock)**
_Monday Dec 11, 2017 at 08:32 GMT_
_Originally opened as https://github.com/dapphub/seth/issues/22_

----

https://github.com/dapphub/seth/blob/290090498f205b5a87ea2b83f487e9b23dd952a9/libexec/seth/seth-calldata#L25

**Comment by asymmetric** [comment]
Don't see why, leaning towards closing this.
