### ISSUE TITLE
Error installing with new script

### ISSUE THREAD

**Issue by brianmcmichael** [dapphub/dapptools#425]
It looks like the installer script was recently updated. Getting the following output on Ubuntu 18.04.

```
bmcmichael@bmcx1c:~/makerdao/ilk-registry$ curl https://dapp.tools/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   715  100   715    0     0   2213      0 --:--:-- --:--:-- --:--:--  2206
sh: 16: [[: not found
sh: 21: [[: not found
sh: 23: cachix: not found
```

**Comment by asymmetric** [comment]
@brianmcmichael do you have nix installed on that machine? The script does not install nix anymore.

**Comment by brianmcmichael** [comment]
Yes. I was able to clone and run the installer directly from the repo, but I think it's an issue with the double brackets not being portable when they are piped into sh. 

I briefly attempted to come up with a solution but got distracted with something else. I can continue to investigate.

**Comment by asymmetric** [comment]
@brianmcmichael Thanks, I can reproduce this on an Ubuntu container, currently investigating why it's happening.

**Comment by asymmetric** [comment]
@brianmcmichael could you give this a try:

```
curl -sS https://raw.githubusercontent.com/dapphub/dapp-tools/fix-install/install | sh
```

**Comment by asymmetric** [comment]
@brianmcmichael should be fixed, thanks for the report!
