### ISSUE TITLE
tests not executing from ETH_FROM address during RPC calls

### ISSUE THREAD

**Issue by realisation** [dapphub/dapptools#443]
I just got back to running kovan tests and what I was using in march doesn't work anymore 

this is my script, nothing fancy, just running hevm with --rpc and setting env vars correctly
```
#!/usr/bin/env bash
source .sethrc && dapp build && DAPP_TEST_NUMBER=$(seth block latest number) DAPP_TEST_TIMESTAMP=$(seth block latest timestamp) hevm dapp-test --rpc $ETH_RPC_URL --json-file="out/dapp.sol.json" --verbose 2 --match $1
```
`ETH_FROM` is in my `.sethrc`

in the past, this made my tests run as if from that address, so I had access to my token balances on the kovan network

what's the way to do it now? I'm on dapp `0.27.0` and hevm `0.38` (so I didn't have to wait for solc 0.5.15 to install each time - but that's another issue)

**Comment by realisation** [comment]
i'll make a PR with docs when its figured out

**Comment by realisation** [comment]
Aha, it is `DAPP_TEST_ADDRESS` now.

There's a lot of .sethrc that isn't documented, and these are used between the different parts off dapp - `dapp` `hevm` and `seth` 

Where would be a good place to place a `.sethrc` readme detailing all of that?

**Comment by realisation** [comment]
Actually this one is doc'd in the HEVM readme

**Comment by xwvvvvwx** [comment]
> Where would be a good place to place a .sethrc readme detailing all of that?

I think [this section](https://github.com/dapphub/dapptools/tree/master/src/seth#configuration) of the `seth` readme would be a great place to document all the possible config settings.
