### ISSUE TITLE
non-derministic branching when backstepping during symbolic execution

### ISSUE THREAD

**Issue by xwvvvvwx** [dapphub/dapptools#456]
I came across some bytecode that seems to have non deterministic branching behaviour. If I step forwards through the program I see only one branch point, but if I step forwards and then backwards and then forwards again across a `JUMPI` I am asked to choose a branch when stepping forwards across the `JUMPI` for the second time only.

I can only reproduce this behaviour after backstepping. It seems to be reproducible with `z3` and `cvc4`, although in the test program below I observed the non deterministic branching with `z3` at both PC13 and PC18, and with `cvc4` at PC13 only.

The test program was built from the following yul code:

```
{
    calldatacopy(0,0,1024)
    let y := mload(0x20)
    for {} and(y, 8) { pop(y) } {
        if y { continue }
        y := 0
    }
}
```

*Steps To Reproduce*

1. `hevm symbolic --code 61040060006000376020515b60088116156027578015601c576021565b600090505b8050600b565b50 --debug`
2. Step forwards until the first `JUMPI` at pc 13
3. Press `0` (do not jump)
4. Step forwards and backwards through the loop a few times

*Results*

After a while the user is non-deterministicaly asked to select a branch when stepping forwards over the `JUMPI` on PC13 or PC18.

**Comment by MrChico** [comment]
Hmm, is this really non-deterministic though? I'm occassionally asked to choose a branch at 13 or 18 but it seems to happen after a couple of iterations, so the query would be different. As can be seen in [askSMT](https://github.com/dapphub/dapptools/blob/master/src/hevm/src/EVM.hs#L1474), we identify queries based on their codelocation and the number of times we have seen that codelocation before. I think this should be sufficient to distinguish them properly

**Comment by xwvvvvwx** [comment]
hmmm I thought it was non deterministic because I could only repro the issue after backstepping? Could you get it to happen without stepping backwards?

**Comment by MrChico** [comment]
Ah, no, I think you are right... Something weird is going on here

**Comment by MrChico** [comment]
Precise instructions to reproduce:
```
hevm symbolic --code 61040060006000376020515b60088116156027578015601c576021565b600090505b8050600b565b50 --debug
```
1. `e`: Step to first branching point
2. `0`: Choose no jump.
3. `n*` until arriving at pc 11.
4. `p`: once, stepping back to pc 10.
5. `n`: until arriving at branch again at pc 13.

Notice that without backstepping, skipping step 4, the jumpi query at pc 13 will be resolved without a user input.
