### ISSUE TITLE
Symbolic: execute with 1024 bytes of calldata

### ISSUE THREAD

**Issue by xwvvvvwx** [dapphub/dapptools#478]
As discussed in https://github.com/dapphub/dapptools/pull/465#discussion_r463944958, `hevm symbolic` used 256 bytes instead of the advertised 1024 bytes when called without a user specified calldata.

Bumping to `1024` with the current architecture imposes a pretty intense performance penalty, but we should aim to increase this (perhaps if / when we start using fully abstracted smt arrays for calldata?).

Also @MrChico my understanding was that 1024 was the max allowable calldata, but I searched a bit and couldnt find an EIP for that, was I mistaken or do you have a reference?

**Comment by MrChico** [comment]
No, calldata can be way larger than that I think

**Comment by xwvvvvwx** [comment]
Oh I see, then it would seem preferable to execute with fully abstracted calldata?

**Comment by MrChico** [comment]
Yeah, I only had to put a limit to it because of the way we are faking dynamic calldata at the moment.
Expanding the range of calldata is basically the same task as supporting dynamic calldata & memory

**Comment by xwvvvvwx** [comment]
For reference:

- `geth` rejects transactions larger than 128KB ([ref](https://github.com/ethereum/go-ethereum/blob/04926db204232b7103b8eb14bf3f8e9de129ad44/core/tx_pool.go#L51))
- `openEthereum` seems to have a limit of 300KB ([ref](https://github.com/openethereum/openethereum/blob/00d47c17b267f67a2d57f6f33267c98f1ad9090d/ethcore/types/src/engines/params.rs#L26))

afaict these are not consensus parameters, but rather limits on what a client will accept or propogate by default, so I think you could still include a larger tx if you were a miner running a custom client.
