### ISSUE TITLE
Trying to build with Solidity version

### ISSUE THREAD

**Issue by ishaansinghal** [dapphub/dapptools#493]
Hi,

I installed dapp to build an existing smart contract, but keep running into this error whenever I run dapp --use solc:0.5.15 build: 

Error: Source file requires different compiler version (current compiler is 0.5.15+commit.6a57276f.Darwin.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.6.7;

Not sure what to do here, thanks for any help!

**Comment by MrChico** [comment]
if you are compiling a contract that wants `0.6.7` then you should use `dapp --use solc:0.6.7 build`
