### ISSUE TITLE
EIP-214: STATICCALL

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#5]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Thursday Sep 14, 2017 at 07:57 GMT_
_Originally opened as https://github.com/dapphub/hevm/issues/14_

----

Implement `STATICCALL`.

**Comment by rainbreak** [comment]
This was done in hevm 0.14
