### ISSUE TITLE
contract not found 

### ISSUE THREAD

**Issue by fxfactorial** [dapphub/dapptools#505]
awesome tool - 
running 

```
> hevm version 
0.41.0
```

(also fwiw - I tried compiling from source which failed on compilation error, then i tried the stack way , which failed as well, only the nix way worked)

I'm trying the example of debugging a mainnet txn 

```
hevm exec \
     --caller $(seth tx $TXHASH from) \
     --address $(seth tx $TXHASH to) \
     --calldata $(seth tx $TXHASH input) \
     --rpc $ETH_RPC_URL \
     --block $(($(seth tx $TXHASH blockNumber)-1)) \
     --gas $(seth tx $TXHASH gas) \
     --debug
```

where the TXHASH is a failed mainnet txn and the RPC is against my local network's running geth node

but running it, i get 

```
hevm: contract not found: <MY_CONTRACT_ADDR>
```

and that isn't the case because this contract addr does exist 

1) Could it be somehow related to how i run my geth node? I run it with 

```
geth \
    --syncmode=fast \
    --http \
    --http.addr 'SOMETHING' \
    --http.port 9550 \
    --ws \
    --ws.addr 'SOMETHING' \
    --ws.port 9551 \
    --ws.origins SOMETHING \
    --datadir="$(pwd)" \
    --cache=12096 \
    --port 30304 \
    --maxpeers 256 \
    --http.vhosts SOMETHING
```

i deployed the contract successfully with this node and it is fully synced

2) Can instead just supply the code of the contract? since i have it locally myself , but still debug the mainnet failed txn?

**Comment by MrChico** [comment]
1.  Hmm, I'm not sure why you wouldn't find the contract. Can you confirm that it exists on the address you imagine by running `seth code <MY_CONTRACT_ADDR>`, with ETH_RPC_URL pointing to your node? It could be an issue with the port or something.

2. Yes. If you have the code available simply provide it as `hevm exec --code $(<A.bin-runtime)`. `--code` has higher priority than (`--address` +  `--rpc`).
If you compile the contract with 
```solc --combined-json=bin,bin-runtime,ast,metadata,abi,srcmap,srcmap-runtime,storage-layout <MY_CONTRACT>.sol > combined.json
```
you can also see the source while stepping through the code if you provide the flag `--json-file combined.json`

**Comment by fxfactorial** [comment]
Thanks for reply 

1. worked, i did 
```
seth code <MY_CONTRACT_ADDR> --rpc-url <MY_LOCAL_NODE> 
```

and it spit out the bytecode just fine 

will try out 2

**Comment by fxfactorial** [comment]
okay cool - i have it working via 

```
hevm exec \
     --caller <CALLER_ADDR> \
     --address <MY_CONTRACT_ADDR> \
     --block $(($(seth tx $TXHASH blockNumber)-1)) \
     --gas $(seth tx $TXHASH gas) \
     --debug \
     --calldata <MY_CALLDATA> \
     --code <MY_CONTRACT_BYTE_CODE>
```

**Comment by MrChico** [comment]
Great! Still not clear to me what makes you unable to fetch state from your local node though...

**Comment by fxfactorial** [comment]
yea - its odd - not sure - you can close if like, but it does seem like an open bug
