### ISSUE TITLE
right way to upgrade?

### ISSUE THREAD

**Issue by fxfactorial** [dapphub/dapptools#506]
my nix skills a bit rusty - but is this sufficient to upgrade hevm if there are updates?

```
$ nix-channel --update nixpkgs
$ nix-env -u '*'
```

or is it better to just run the ` install | sh ` command again?

**Comment by MrChico** [comment]
The command `nix-env -u '*'` will update all of the packages installed via a channel I believe, whereas this repo has custom written derivations for the relevant programs. To update the tools provided here, you have to specify the path to these derivations. 
If you want the bleeding edge, here's how we build from source:
```
git clone git@github.com:dapphub/dapptools.git # or pull latest master
cd dapptools && nix-env -iA solc dapp seth hevm -f .
```
Or you can also just run the `install | sh` again, which basically does the above with extra steps (fetches latest release tag)

**Comment by fxfactorial** [comment]
cool - thank you - so i will just use the install script again
