### ISSUE TITLE
Balance is increased when executing empty functions with positive gas price

### ISSUE THREAD

**Issue by ggrieco-tob** [dapphub/dapptools#511]
In the latest revision (0afd97e739ec0e38e5a47c1efc24abcf2217660f), executing an empty function allows `msg.sender` to increase its balance when gas price is positive (e.g. 1). To reproduce, create a new dapp project and use `src/Test.t.sol` like this one:

```solidity
pragma solidity ^0.5.7;

import "ds-test/test.sol";

contract TestTest is DSTest {
    uint balance;
    address sender;

    constructor () payable public {
        sender = msg.sender;
        balance = msg.sender.balance;
    }

    function setUp() public { /* this function is expected to be empty */}

    function test_basic_balance() public {
        assertTrue(sender == msg.sender && balance == msg.sender.balance);
    }
}

```

Then you can run `dapp test` like this:

```
$ DAPP_TEST_GAS_PRICE=0 dapp test
...
Running 1 tests for src/Test.t.sol:TestTest
[PASS] test_basic_balance() (gas: 2601)

$ DAPP_TEST_GAS_PRICE=1 dapp test
...
Running 1 tests for src/Test.t.sol:TestTest
[FAIL] test_basic_balance()

Failure: test_basic_balance
  
  "Assertion failed"
```

**Comment by MrChico** [comment]
Thanks for reporting @ggrieco-tob , I think the problem is that currently `msg.sender` is not charged for the initial gas cost, but still rewarded the remaining gas after successful calls. We should make sure to charge for the initial gas cost which should ensure that the msg.sender balance will not increase. But I don't think that the test case you have given will hold as currently stated even with this change. But the weaker `assertTrue(msg.sender.balance <= balance);` would.

**Comment by ggrieco-tob** [comment]
> But I don't think that the test case you have given will hold as currently stated even with this change. But the weaker assertTrue(msg.sender.balance <= balance); would.

So, this means that the `msg.sender` should have enough balance to make a call, or the call will revert? (I don't think older hevm versions had this feature).

**Comment by MrChico** [comment]
That's right. Older versions of hevm did not perform transaction finalization when doing unit tests, so they did not charge or refund gas. Now we do finalization, but missed charging the initial gas cost.
I think it's reasonable to charge the caller for gas, but we should set default values so it can always afford it
