### ISSUE TITLE
ethsign not installed with the one-line installer

### ISSUE THREAD

**Issue by dmintercept** [dapphub/dapptools#535]
curl https://dapp.tools/install | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   802  100   802    0     0   2271      0 --:--:-- --:--:-- --:--:--  2271
Configured https://dapp.cachix.org binary cache in /home/snevins/.config/nix/nix.conf
replacing old 'dapp-0.30.0'
replacing old 'hevm-0.42.0'
replacing old 'seth-0.9.2'
replacing old 'solc-0.6.7'
installing 'dapp-0.30.0'
installing 'hevm-0.42.0'
installing 'seth-0.9.2'
installing 'solc-0.6.7'
All set!

**Comment by MrChico** [comment]
`ethsign` isn't made available directly by the install script (it is only installed as a dependency of seth). To install it directly, you can do:
```
nix-env -iA ethsign -f $(curl -sS https://api.github.com/repos/dapphub/dapptools/releases/latest | jq -r .tarball_url)
```
