### ISSUE TITLE
dapp was working 

### ISSUE THREAD

**Issue by kissdaddy23** [dapphub/dapptools#563]
We tested it to make sure it was working, now when we sign back in, dapp doesen't work anymore. Get the error command not found . Do you have to reinstall it everytime? Or what is the issue? Thank you

**Comment by MrChico** [comment]
sign back in where?

**Comment by kissdaddy23** [comment]
trying to figure it out thanks mr chico. Think its because we didnt create ~/ .profile only added . /Users/username/.nix-profile/etc/profile.d/nix.sh to the terminal

**Comment by MrChico** [comment]
Right.. so do you need to run:
```
. "$HOME/.nix-profile/etc/profile.d/nix.sh
```
again?

**Comment by kissdaddy23** [comment]
yes then it works

**Comment by kissdaddy23** [comment]
ok we figured it out for anybody who has this problem you must go into your terminal preferences. click on shell. enter said code thats similar to this . /Users/username/.nix-profile/etc/profile.d/nix.sh underneath run command. Then it should work everytime.
