### ISSUE TITLE
dapp---use: Could not find solc-0.5.12 in your path.

### ISSUE THREAD

**Issue by wilbarnes** [dapphub/dapptools#564]
i reinstalled dapptools and now get this error

trying various dapp commands: `dapp test`, `dapp build`:

```
dapp---use: Could not find solc-0.5.12 in your path.
dapp---use: Try `nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc-0.5.12`
dapp---use: in your dapptools repo.
```

i try to run that command and: 
`error: attribute 'solc-0' in selection path 'solc-static-versions.solc-0.5.12' not found`

**Comment by MrChico** [comment]
There's an unfortunate typo here which is fixed on master. Try
```
nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc-0_5_12`
```

**Comment by wilbarnes** [comment]
i thought that too after checking solc-static-versions but that also gives me the same error:
`error: attribute 'solc-0_5_12' in selection path 'solc-static-versions.solc-0_5_12' not found`

**Comment by MrChico** [comment]
Oops, I meant:
`solc_0_5_12`

**Comment by wilbarnes** [comment]
that works thank u

**Comment by brianmcmichael** [comment]
This was helpful.

This new system seems a little clunky, we're often switching between testing 0.6.7 and 0.5.12 (and others) depending on the repo, and when I update using the above command to 0.6.7, 0.5.12 is removed from my path and I have to re-run this command. Somehow the old method kept all of the versions in the path.

Note: I *am* using [solc-select](https://github.com/crytic/solc-select) on my system for non-dapp related projects, and I'm not sure if that's part of the conflict, but it didn't conflict before.

**Comment by MrChico** [comment]
Hmm, that is not the expected behaviour, @brianmcmichael . Can you clarify some things for me:
- are you running macos?
- when installing from dapptools, are you installing the static solc binary (as in the command above?) or the nix package version (`solc-versions.solc_0_5_12`)?

Note that you can also pass a path to the executable as argument to `--use`

**Comment by rainbreak** [comment]
@brianmcmichael you can also install all of the versions at once with 

```
nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions
```

**Comment by rainbreak** [comment]
> Note: I am using solc-select on my system for non-dapp related projects, and I'm not sure if that's part of the conflict, but it didn't conflict before.

Normally dapp will use a solc that is provided by nix, but you can also have it use a binary directly. For example, if `solc` is in your path and is the solc that you want, these would all work:

```
DAPP_SOLC=solc dapp build
DAPP_SOLC=`which solc` dapp build
dapp --use `which solc` build
```

**Comment by brianmcmichael** [comment]
@MrChico I'm on ubuntu 18.04 base, had just used the dapptools installer script from the dapp.tools site.

I seem to be back up and running with the command from @rainbreak 

Would it be worthwhile to add that at the end of the installer script?

Thanks!

**Comment by rainbreak** [comment]
@brianmcmichael perhaps it does make sense to have all versions installed by default yes. The reason not to is that it's just a lot of binaries to download.
