### ISSUE TITLE
Solc 0.8.0 support?

### ISSUE THREAD

**Issue by ethernomad** [dapphub/dapptools#578]
Is it possible to support Solidity 0.8.0?

I get the following error:

```
+ dapp clean
+ rm -rf out
+ /usr/bin/solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime,ast,metadata,storage-layout /=/ src/AcuityAtomicSwap.sol src/AcuityAtomicSwap.t.sol
hevm: (^?!): empty Fold
CallStack (from HasCallStack):
  error, called at src/Control/Lens/Fold.hs:1285:28 in lens-4.17.1-OI9xiiJY6KIEwKnz7hWvu:Control.Lens.Fold
  ^?!, called at src/EVM/Solidity.hs:308:20 in hevm-0.43.2-8eMII8enSM738p5iKSIGjk:EVM.Solidity
```

There are some changes to the solc output: https://github.com/ethereum/solidity/blob/develop/Changelog.md#080-2020-12-16

**Comment by MrChico** [comment]
Hey @ethernomad , I believe this would be supported by #569. Can you build it (for example with `nix-env -f https://github.com/dapphub/dapptools/archive/standardjson.tar.gz -iA dapp`) and see if this resolves your problem?

**Comment by ethernomad** [comment]
That build succeeded, but I get the same error. Do I need to do something different to run the new binary?

**Comment by MrChico** [comment]
No, if your `dapp` was installed with the standard build script it should sit in your nix-env and would be overwritten by the command above. I am able to build `0.8.0` projects on that branch though. Can you share a minimal example that is broken and I'll try to replicate?

**Comment by ethernomad** [comment]
It works now.

**Comment by MrChico** [comment]
Great, thanks!
