### ISSUE TITLE
`hevm` flatten includes multiple SPDX headers

### ISSUE THREAD

**Issue by brianmcmichael** [dapphub/dapptools#583]
`hevm --flatten` generates a concatenated output of project source files. This currently includes all SPDX headers in dependent files. These headers are required by later versions of solidity, but multiple SPDX headers in a file will cause compilation to fail. This is an issue when the flattened file is used for etherscan verification or otherwise compiled from the flattened source.

The expected functionality would probably need to remove all headers and concatenate conflicting SPDX headers into a single SPDX header at the top of the file.

**Comment by MrChico** [comment]
Hmm, can you provide an example where compilation fails? Multiple SPDX headers seem to compile for me.

**Comment by brianmcmichael** [comment]
Yes, the compilation works, it's the flattened file that won't compile if there are multiple SPDX headers. I should mention that we're targeting 0.6.11, and I don't think this issue appears in 0.6.7. Currently I can deploy a contract with `seth` just fine, but when I `hevm -flatten` the code and attempt to verify the contract on etherscan, or attempt to compile the flattened file directly, the solidity compiler errors due to the presence of multiple SPDX headers in the source.

This is only for contracts that have a SPDX header and which inherit other contracts that also have SPDX headers. The solution right now is to manually edit out the extra headers in the flattened result, however this issue is a little tricky to resolve because I would tend to resolve it by adopting the license of the compilation target, but I think the standard says that the headers should be merged in the same way that the pragmas are.

According to the [SPDX FAQ](https://wiki.spdx.org/view/SPDX_FAQ):

* How does one represent a file that is licensed under two or more licenses?
   * SPDX license information can be represented using conjunctive or disjunctive regular expressions. For example, a file that is subject to the Apache-2.0, MIT and GPL-2.0 would be represented using the following conjunctive expression: (Apache-2.0 and MIT and GPL-2.0)

**Comment by MrChico** [comment]
If you provide a minimal example for me to replicate I can take a look at this. I tried flattening files with multiple SPDX headers and the flattened file compiled fine

**Comment by gbalabasquer** [comment]
So what Brian means is if you use that flattened code for example in Remix and you try to compile it, it will return this error:
```
ParserError: Multiple SPDX license identifiers found in source file. Use "AND" or "OR" to combine multiple licenses. Please see https://spdx.org for more information.
```
Same thing happens if you want to use that code for verifying in Etherscan.

Example: https://gist.github.com/gbalabasquer/efa08f79d7f8ea738b94c8555f8dd7ff

**Comment by MrChico** [comment]
Ok. Am able to reproduce, thx
