### ISSUE TITLE
Dapp init is broken

### ISSUE THREAD

**Issue by montyly** [dapphub/dapptools#595]
Hi,

Since the latest release ([0.44.0](https://github.com/dapphub/dapptools/releases/tag/hevm%2F0.44.0)), `dapp init` is broken:

```
$ curl https://dapp.tools/install | sh
$ mkdir dapp_test
$ cd dapp_test
$ dapp ini
[...]
dapp test
src/Dapptests.t.sol:3:1: ParserError: Source "ds-test/test.sol" not found: File not found.
import "ds-test/test.sol";
^------------------------^
```

I haven't looked into the changes, but I am assuming `ds-test/test.sol` was moved, or is no longer present. 

There is a `lib/ds-test/src/test.sol` in the directory, but I am not sure what are the expected import rules here.

**Comment by MrChico** [comment]
Thanks for reporting. #596 fixes this.

**Comment by montyly** [comment]
Thanks @MrChico for the quick fix!

Do you have an estimate for the next `dapp` release?

**Comment by MrChico** [comment]
Yeah, we will release when we merge #597

**Comment by xwvvvvwx** [comment]
@montyly we just released a new version of `dapp`.

**Comment by lucadonnoh** [comment]
i still have this issue

**Comment by transmissions11** [comment]
> i still have this issue

You sure it's not just in your IDE? Might have to do this if you're using VSCode: https://twitter.com/transmissions11/status/1434963080971124737?s=21
