### ISSUE TITLE
EIP-196 & EIP-197: new elliptic curve precompiled contracts

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#6]
<a href="https://github.com/mbrock"><img src="https://avatars3.githubusercontent.com/u/8154?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mbrock](https://github.com/mbrock)**
_Thursday Sep 14, 2017 at 10:23 GMT_
_Originally opened as https://github.com/dapphub/hevm/issues/15_

----

https://github.com/paritytech/parity/pull/5307/files

https://hackage.haskell.org/package/mcl

seems pretty tricky to me

**Comment by rainbreak** [comment]
This was done #213
