### ISSUE TITLE
Standard JSON is not loading

### ISSUE THREAD

**Issue by hexonaut** [dapphub/dapptools#610]
Running this command: `DAPP_STANDARD_JSON="config.json" dapp --use solc:0.6.11 build` gives me the following error with a freshly generated standard json config.json:

```
+ dapp clean
+ rm -rf out
* Line 1, Column 1
  Syntax error: value, object or array expected.
* Line 1, Column 1
  A valid JSON document must be either an array or an object value.

make[1]: *** [all] Error 1
make: *** [deploy] Error 2
```

**Comment by hexonaut** [comment]
Found the issue:

https://github.com/dapphub/dapptools/blob/346a562d3af8ef7fd9a28b13c7409dd3141b3ea3/src/dapp/libexec/dapp/dapp-build#L64

Removing the dash (-) at the end of the command works.

**Comment by xwvvvvwx** [comment]
Much appreciated @hexonaut :pray: :sparkles:
