### ISSUE TITLE
min / max bound modifiers for ds-test

### ISSUE THREAD

**Issue by xwvvvvwx** [dapphub/dapptools#622]
We currently have two ways to restrict the input range of numeric types when fuzzing:

1. by using sized types (e.g. `uint8`, `int56`, etc)
2. by using mod (e.g. (`in % 100`)

Both of these methods are only useful for defining an upper bound for generated values, and do not support defining a lower bound. 

We could perhaps introduce some modifiers into `ds-test` that would allow very granular control over the range of generated values, perhaps something like this?

```solidity
function test_fuzz(uint x, int y) public bounds(x, 150, 2000) bounds(y, 1 ether, 200 ether) {
    assertEq(x, y);
}
```

The semantics `bounds(x, 150, 2000)` would be smth like: "when generating values for `x`, use `150` as a lower bound and `2000` as an upper bound". The modifier would be read from the solidity AST by `hevm` during test execution, and the values would be passed into the number generator as lower / upper bounds.

**Comment by MrChico** [comment]
we can use the [`testopts`](https://github.com/dapphub/ds-test/blob/master/src/test.sol#L45) modifier for this instead of introducing a new one

**Comment by livnev** [comment]
It's pretty easy to use `%` for lower bounds. e.g. `bounds(x, 150, 2000)` could simply be defined in solidity as:
```
x = 150 + x % (2000 - 150)
```

**Comment by xwvvvvwx** [comment]
ah yes of course, had missed that, we could probably just add this as solidity helper function in ds-test in that case
