### ISSUE TITLE
hevm fails with assembly in Proxy contract

### ISSUE THREAD

**Issue by cmditch** [dapphub/dapptools#64]
SSCCE - https://gist.github.com/cmditch/91ec92296f90ef0c7c97d0432c95c20c

(Not DSProxy. This is a Proxy contract from Stefan @ Gnosis)

`dapp test` results in.

```
FAIL testFoo()

Failure: testFoo
  
  src/ProxyTest.t.sol:ProxyTest
   ├╴constructor
   ├╴initialize test
   │  ├╴create Foo (src/ProxyTest.t.sol:18)
   │  └╴create Proxy (src/ProxyTest.t.sol:19)
   └╴testFoo()
      ├╴call Proxy::[unknown method](0x037a417c) (src/ProxyTest.t.sol:24)
      │  └╴error OutOfGas 0xfbfffffff4c4 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff (src/Proxy.sol:32)
      └╴error Revert <source not found>
```

**Comment by rainbreak** [comment]
This proxy does the delegatecall passing `not(0)` as the gas available, which is the whole wordsize and seems like a hack. If you replace that with `sub(gas, 703)` the test will pass, as this is the actual gas available minus the delegatecall overhead.

I'm not sure what the defined behaviour is here without looking at the yellow paper. Does it work with geth / parity?

**Comment by cmditch** [comment]
Thanks for the quick response @rainbreak! Good find on the assembly code. I'll paste a few reference links below regarding the origination of this contract code.

I've updated the code with your suggested change. The OutOfGas error is no more, but erroneous behavior still occurs.

[Here is a gist](https://gist.github.com/cmditch/cedd81e853be9a1b831622ad69b6d80b) to try with dapp test.
[Here is a similar gist](https://gist.github.com/cmditch/fea2fd934aa62c68eaab8e07d453a3ba) that can easily be tested against geth, remix, parity, etc. (I've tested functionality on Rinkeby, a local geth node, remix JS vm, and ganache with no errors).

```
Running 2 tests for src/ProxyTest.t.sol:ProxyTest
PASS testFooMaster() (gas: 3061)
FAIL testFooProxy()

Failure: testFooProxy
  
  "Error: Wrong `uint' value"
    Expected: 42
      Actual: ~1.57294584e75
  
  src/ProxyTest.t.sol:ProxyTest
   ├╴constructor
   ├╴initialize test
   │  ├╴create Foo (src/ProxyTest.t.sol:58)
   │  └╴create Proxy (src/ProxyTest.t.sol:59)
   └╴testFooProxy()
      ├╴call Proxy::[unknown method](0x037a417c) (src/ProxyTest.t.sol:68)
      │  ├╴call Foo::testFunc()() (src/ProxyTest.t.sol:34)
      │  │  └╴← uint256 0x
      │  └╴← 0x037a417c00000000000000000000000000000000000000000000000000000000
      ├╴log_bytes32("Error: Wrong `uint' value") (lib/ds-test/src/test.sol:112)
      ├╴log_named_uint("  Expected", 42) (lib/ds-test/src/test.sol:113)
      └╴log_named_uint("    Actual", 1572945844198690166654652573502116276175073521308400342885302740072649457664) (lib/ds-test/src/test.sol:114)
```

Thanks!

**Comment by livnev** [comment]
@cmditch running the [gist you provided](https://gist.github.com/cmditch/cedd81e853be9a1b831622ad69b6d80b) with `dapp test` has both tests succeeding:

```
$ dapp test
+ dapp clean
+ rm -rf out
+ solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --abi --bin --bin-runtime = -o out/ src/ProxyTest.t.sol
src/ProxyTest.t.sol:47:3: Warning: Function state mutability can be restricted to pure
  function testFunc() public view returns(uint) {
  ^ (Relevant source part starts here and spans across multiple lines).
+ solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime,ast = src/ProxyTest.t.sol
src/ProxyTest.t.sol:47:3: Warning: Function state mutability can be restricted to pure
  function testFunc() public view returns(uint) {
  ^ (Relevant source part starts here and spans across multiple lines).
+ solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --abi --bin --bin-runtime = -o out/ src/ProxyTest.sol
+ solc --overwrite ds-test/=lib/ds-test/src/ ds-test=lib/ds-test/src/index.sol --combined-json=abi,bin,bin-runtime,srcmap,srcmap-runtime,ast = src/ProxyTest.sol
Running 2 tests for src/ProxyTest.t.sol:ProxyTest
PASS testFooMaster() (gas: 3061)
PASS testFooProxy() (gas: 5266)
```

Are you sure everything is OK with your set up and you are testing the same source code? What is your version of `dapp`? I have:
```
$ dapp --version
dapp 0.9.0
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```

**Comment by cmditch** [comment]
@livnev how odd. Mine is the same (barring clang/g++):

```
λ dapp --version
dapp 0.9.0
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Darwin.clang
```

also
```
λ ls $(which hevm)
lrwxr-xr-x  1 root  wheel    62B Dec 31  1969 /Users/cmditch/.nix-profile/bin/hevm -> /nix/store/m01yj3cva83r3vmh72lq3fh58zifsnzv-hevm-0.15/bin/hevm
```

**Comment by cmditch** [comment]
Alright, back in action. Did a full reinstall of dapp/solc/nix. Proxy tests are working now.

Experiencing some lockups with `hevm`, seems to be in instances where the call stack depth gets quite large - but this is probably a whole other issue - refactoring code has helped so far.

Thanks!
