### ISSUE TITLE
'dapp build'  -   include the colors in the std output json for solc

### ISSUE THREAD

**Issue by henry-hz** [dapphub/dapptools#659]
Dears, first of all, I am a big fan of dapptools!

I would like to ask if it would be  possible to include the colors in the std output json. Solc has an amazing color output that helps a lot to differentiate between warnings, errors, etc....

**Comment by MrChico** [comment]
Thank you! The colors aren't perserved in the standard-json error output, unfortunately. Cf. https://github.com/ethereum/solidity/issues/2768

**Comment by cameel** [comment]
Here's an issue specifically about colors: https://github.com/ethereum/solidity/issues/11507. Any feedback would be appreciated.
