### ISSUE TITLE
dapp install a specific version of a GitHub repo's release

### ISSUE THREAD

**Issue by TimDaub** [dapphub/dapptools#662]
I'm trying to install e.g. [OpenZeppelin/openzeppelin-contracts@3.1.0](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v3.1.0). Though there's an issue with OZ's way of structuring their repo (#27), with `dapp install` I'm able to install their code into the `lib` dir of my dapp.

But let's say I wanted to install a specific version of their code, e.g. 3.1.0? How would I do that? I tried several syntaxes (e.g. `dapp install openzeppelin-contracts@3.1.0` but it didn't work).

**Comment by xwvvvvwx** [comment]
We've been discussing something like this for a while, as well as syntax that would allowing importing a specific version. Definitely agree that it would be nice.

For now you can `cd` into `lib/openzeppelin-contracts` and use `git checkout` to checkout the submodule to whichever tag / commit you need.

**Comment by TimDaub** [comment]
> For now you can `cd` into `lib/openzeppelin-contracts` and use `git checkout` to checkout the submodule to whichever tag / commit you need.

Was about to make that exact suggestion. I assume that since this checkout is tracked through git submodules, it persists the libraries tag in the project git history, right?

**Comment by xwvvvvwx** [comment]
I believe you will just have a commit hash not a tag ref in the parent repo's git history.

**Comment by TimDaub** [comment]
Even better 😄
