### ISSUE TITLE
function name case isn't consistent

### ISSUE THREAD

**Issue by TimDaub** [dapphub/dapptools#664]
I'm pretty sure this is intentional and not a mistake, but in the tutorial for how to test a dapp, the function case is inconsistent: https://github.com/dapphub/dapptools/tree/master/src/dapp#unit-testing

`setUp` and `test_withdraw`. Personally, I'd prefer it used either or convention but not both.
Can I use `testWithdraw` too?

Edit: apparently, I can.

**Comment by MrChico** [comment]
yup, but you can not use `set_up`

**Comment by MrChico** [comment]
I don't really see this as a particular issue, so I'll close this, but if it really bothers you then you're welcome to improve the tutorial with a PR :)
