### ISSUE TITLE
Track gas cost of function-to-test

### ISSUE THREAD

**Issue by TimDaub** [dapphub/dapptools#665]
In unit testing, usually a function is tested multiple times with different inputs. dapptools tracks the gas usage of each unit test function that is being executed and later shows it in the test results:

```bash
[PASS] testDeposit() (gas: 108226)
```

However, what's important to mention here is that `testDeposit`'s gas usage is 108226. The unit tested function [`deposit`](https://github.com/rugpullindex/honeybatcher/blob/7821a09db8fe99d22b2d5538ffc6501745a825a3/src/Honeybatcher.sol#L15) that is called from within `testDeposit` can have a much lower gas cost as e.g. setting up `deposit`'s parameters in production can be done off-chain.

As a user of dapptools, it'd be super helpful to understand the gas usage of a function within a unit test. Ideally with a simple glance towards the tests's results. It's because then, it'd empower me to optimize the gas usage of each of my contract's functions deliberately (e.g. I could do trial and error to see that `external` + `calldata` is cheaper than `public` + `memory`).

What could be a solution to this functionality? Could I be capable of doing it already?
I could just execute all setup code in the `setUp` function. However, this is against the philosophy of writing atomic unit tests. Are there any other options? Is there maybe a way where hevm only tracks gas usage of functions that are not `*.t.sol`?

**Comment by MrChico** [comment]
There is not a direct way of doing this, but logging gas before and after a function call is usually a good enough approach:
```
function testDeposit() public {
prep();
uint startGas = gasleft();
c.deposit();
uint endGas = gasleft();
emit log_named_uint("deposit gas", startGas - endGas);
}
```

**Comment by TimDaub** [comment]
That's great, thanks.

**Comment by TimDaub** [comment]
Hey I looked into this but one of the problems I see with this approach is that `--verbosity=3` and tracing the emitted event in the stack is required. Rather, I'd prefer a clear overview of my tests and how much gas my functions are consuming. Is it maybe possible to overwrite the value of ds-test's `logs_gas`? to my own value?

**Comment by MrChico** [comment]
> Hey I looked into this but one of the problems I see with this approach is that --verbosity=3 and tracing the emitted event in the stack is required.

I don't understand the problem.

**Comment by TimDaub** [comment]
The problem is that with `--verbosity=3` the test output is, well ... verbose. So to get an overview of how much gas a function of a contract consumes, is tedious. For two functions on a computer with a laptop-sized screen and regular font size, it's probably already necessary to scroll 2 pages and skim with the eyes for the results.

**Comment by d-xo** [comment]
I think the output should be a bit clearer if you use `--verbosity 2`?

**Comment by TransmissionsDev** [comment]
> I think the output should be a bit clearer if you use `--verbosity 2`?

Two is fairly clean, though all the "Success: test______" messages are a little annoying 😅
