### ISSUE TITLE
label dapptools docs as outdated

### ISSUE THREAD

**Issue by TimDaub** [dapphub/dapptools#666]
see website: https://dapp.readthedocs.io/en/stable/index.html

see comment from contributor: https://github.com/dapphub/dapptools/issues/18#issuecomment-865112985

To make users aware (options):

- take docs offline
- update docs
- label them as deprecated
- ...

**Comment by d-xo** [comment]
yes, very interested in taking this page offline. The issue is unfortunately figuring out who actually has access to this page to delete it :disappointed:

**Comment by d-xo** [comment]
It's gone :slightly_smiling_face:
