### ISSUE TITLE
-vv is a noop

### ISSUE THREAD

**Issue by TransmissionsDev** [dapphub/dapptools#670]
At least from a user's perspective `-vv` currently has no effect. The output from `dapp test -vv` is currently the same as just `dapp test`. 

`dapp test --verbosity 3` still works.

**Comment by TransmissionsDev** [comment]
There's also still some references to `-vvv` in the `dapp` binary which does not seem to be in-use anymore.

**Comment by TransmissionsDev** [comment]
https://github.com/dapphub/dapptools/pull/657 <-- this might solve this issue?

**Comment by d-xo** [comment]
fixed by: https://github.com/dapphub/dapptools/pull/676
