### ISSUE TITLE
DAPP_BUILD_OPTIMIZE/DAPP_BUILD_OPTIMIZE_RUNS do not do anything in .dapprc

### ISSUE THREAD

**Issue by TransmissionsDev** [dapphub/dapptools#672]
`DAPP_BUILD_OPTIMIZE` and `DAPP_BUILD_OPTIMIZE_RUNS` does nothing if set in `.dapprc`

With a makefile like this,

```make
# Dapp Build Config.
export DAPP_BUILD_OPTIMIZE=1
export DAPP_BUILD_OPTIMIZE_RUNS=100000

# Install, update, build and test everything.
all: solc install update build test
# Install proper solc version.
solc:; nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_6
# Install npm dependencies.
install:; npm install 
# Install dapp dependencies.
update:; dapp update

# Compiles the project.
build:; dapp build
# Test the project and only log verbose info for failed tests.
test:; dapp test --verbosity 1
```

and .dapprc like this:

```
DAPP_SOLC_VERSION=0.8.6
DAPP_BUILD_OPTIMIZE=1
DAPP_BUILD_OPTIMIZE_RUNS=100000
```

If I run `make test` you will see that `test_properly_init_erc20` takes up `13625` gas. 

```sh
❯ make test
dapp test --verbosity 1
 dapp-build: building with linked libraries
dapp: Predeploying test library src/libraries/StringConcat.sol:StringConcat at 0x0DdeDfFe2789df61F5f76479464F568334414389
Running 2 tests for src/tests/Vault.t.sol:VaultsTest
[PASS] test_properly_init_erc20() (gas: 13625)
+++ OK, passed 100 tests.
[PASS] test_deposit_withdraw(uint256) (runs: 100)
```

But when running `dapp test` it takes up `18007` gas!

```sh
❯ dapp test
 dapp-build: building with linked libraries
dapp: Predeploying test library src/libraries/StringConcat.sol:StringConcat at 0x0DdeDfFe2789df61F5f76479464F568334414389
Running 2 tests for src/tests/Vault.t.sol:VaultsTest
[PASS] test_properly_init_erc20() (gas: 18007)
[PASS] test_deposit_withdraw(uint256) (runs: 100)
```

This doesn't make sense as they both have the same optimization config, but seemingly dapp is ignoring the optimization config set in `.dapprc`.

If you'd like to try this yourself locally here's a reproduction branch (just run `make`):

https://github.com/Rari-Capital/vaults/tree/dapprc-issues-repro

**Comment by d-xo** [comment]
hmmmm, I think the difference isn't to do with makefiles vs dapprc files, but rather because in the makefile you use `export`, whereas in the `.dapprc` you don't. The difference goes away for me if I use `export` in the `.dapprc`. I guess that this is because the var is not passed down to `dapp mk-standard-json` if `export` isn't used :thinking:.

I'm not sure how to fix this, or if it's even really a bug :thinking:  @MrChico do you have some thoughts?

**Comment by MrChico** [comment]
Its kind of annyoing to have three different places to configure options, flags, env vars and .dapprc files. Personally I wouldnt mind deprecating the .dapprc file, but otherwise it seems like we would need to read the dapprc file and reexport all vars in there

**Comment by TransmissionsDev** [comment]
> Its kind of annyoing to have three different places to configure options, flags, env vars and .dapprc files. Personally I wouldnt mind deprecating the .dapprc file, but otherwise it seems like we would need to read the dapprc file and reexport all vars in there

I definitely would prefer the second idea you proposed there. .dapprc is great, just wish it let you export any env var you want and it would do that right before u run any dapp command.

**Comment by TransmissionsDev** [comment]
> Its kind of annyoing to have three different places to configure options, flags, env vars and .dapprc files. Personally I wouldnt mind deprecating the .dapprc file, but otherwise it seems like we would need to read the dapprc file and reexport all vars in there

I would definitely ask that you guys don't remove `.dapprc` but yea the behavior of it is confusing as you don't have to use the export keyword for solc version and other stuff but you do for optimization? I like the second option of just reexporting all vars set in there.

**Comment by TransmissionsDev** [comment]
Wait why does a dapprc like this:

```
DAPP_SOLC_VERSION=0.8.6
```

Even work in the first place?

Just looked at the `dapp` source and it looks like it just runs `. $(pwd)/.dapprc`, wouldn't you *need* an `export` in front of DAPP_SOLC_VERSION`?

**Comment by TransmissionsDev** [comment]
I think the docs should just show an example `.dapprc` file and encourage using `export` to clear up all confusion. Ideally they even explain that the `.dapprc` is really a shell script that gets executed before all `dapp` commands.

**Comment by d-xo** [comment]
> Just looked at the `dapp` source and it looks like it just runs `. $(pwd)/.dapprc`, wouldn't you *need* an `export` in front of `DAPP_SOLC_VERSION`?

hmmmm, good question. I think it's because `DAPP_SOLC_VERSION` is read directly in the same place that the `.dapprc` is sourced, whereas other variables are read in a subprocess and so must be exported.

I must admit that this kind of subtle issue (and leakage of implementation detail to config files) does make removing the `.dapprc` mechanism quite tempting, but I guess it probably does have its place, and its better to keep it around (at least until we figure out something better).

Agree that some more docs would be great here.

**Comment by TransmissionsDev** [comment]
Attempted adding some docs here: #685!
