### ISSUE TITLE
Using `dapp install` with a lib that does not use `src` as it's contract directory causes remap errors

### ISSUE THREAD

**Issue by TransmissionsDev** [dapphub/dapptools#674]
I've attempted to install the openzeppelin contracts like how @MrChico did it here:

https://github.com/dapp-org/radicle-contracts-tests

(install using dapp install and configure remaps in remappings.txt).

I can successfully get the project to build and test but I still see this odd compiler error whenever building (it does not seem to halt execution but is still a huge eyesore):

```sh
❯ dapp test
fatal: cannot change to 'lib/openzeppelin-contracts/src': No such file or directory
child_process.js:656
    throw err;
    ^

Error: Command failed: git -C lib/openzeppelin-contracts/src rev-parse HEAD
fatal: cannot change to 'lib/openzeppelin-contracts/src': No such file or directory

    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at run (/nix/store/jzifrfhir5z2j0xavalwkssgx3mi5hjq-dapp-0.32.2/libexec/dapp/dapp-remappings:64:35)
    at /nix/store/jzifrfhir5z2j0xavalwkssgx3mi5hjq-dapp-0.32.2/libexec/dapp/dapp-remappings:35:16
    at Array.forEach (<anonymous>)
    at findRemappings (/nix/store/jzifrfhir5z2j0xavalwkssgx3mi5hjq-dapp-0.32.2/libexec/dapp/dapp-remappings:18:43)
    at Object.<anonymous> (/nix/store/jzifrfhir5z2j0xavalwkssgx3mi5hjq-dapp-0.32.2/libexec/dapp/dapp-remappings:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  status: 128,
  signal: null,
  output: [
    null,
    '',
    "fatal: cannot change to 'lib/openzeppelin-contracts/src': No such file or directory\n"
  ],
  pid: 18610,
  stdout: '',
  stderr: "fatal: cannot change to 'lib/openzeppelin-contracts/src': No such file or directory\n"
}
 dapp-build: building with linked libraries
dapp: Predeploying test library src/libraries/StringConcat.sol:StringConcat at 0x42cc0d98184e27fB7a5033cD5b842a68BFC7014A
Running 2 tests for src/tests/Vault.t.sol:VaultsTest
[PASS] test_properly_init_erc20() (gas: 18007)
[PASS] test_deposit_withdraw(uint256) (runs: 100)

```

The issue appears to stem from `dapp` not knowing how to handle this external dependency having `contracts` as its source directory instead of `src`. Ideally `dapp` should just fail silently here.

To reproduce, simply clone this branch and run `make`:

https://github.com/Rari-Capital/vaults/tree/repro-oz-weird-output

**Comment by d-xo** [comment]
adding `export DAPP_REMAPPINGS=$(cat remappings.txt)` to the top of the makefile fixed this for me.

**Comment by TransmissionsDev** [comment]
> I think you just forgot to set the `DAPP_REMPPAINGS` env var. Adding `export DAPP_REMAPPINGS=$(cat remappings.txt)` to the top of the makefile fixed this for me.

I set the env-var in `.dapprc` which I could tell worked as modifying the remappings file would break the build if done incorrectly. 

Here's a branch of that might be easier to play with (I use `export` in the .dapprc`):

https://github.com/Rari-Capital/vaults/tree/oz-issues-v2-repro

**Comment by TransmissionsDev** [comment]
> I think you just forgot to set the `DAPP_REMPPAINGS` env var. Adding `export DAPP_REMAPPINGS=$(cat remappings.txt)` to the top of the makefile fixed this for me.

Hmm so the issues seems to come from settings `export DAPP_REMAPPINGS=$(cat remappings.txt)` in `.dapprc`. If I set it in my local environment or via a Makefile I will not see that weird error. 

Whats odd is that `DAPP_REMAPPINGS` is definitely set and is picked up by `dapp` (the tests pass and everything), just maybe not early enough? 

So I guess my issue here is that setting `DAPP_REMAPPINGS` in `.dapprc` causes errors but tests still pass.

**Comment by TransmissionsDev** [comment]
Ah yep discovered the root cause.

https://github.com/dapphub/dapptools/blob/f24cab707adda124c0035c97e3c54fe8c9bde773/src/dapp/libexec/dapp/dapp#L106

The DAPP_REMAPPINGS var is read *before* `.dapprc` is loaded in, and since it will be null if set in the `.dapprc` it will try to run `dapp remappings` which causes that little error.

DAPP_REMAPPINGS will be overridden after loading in the `.dapprc` file which is why the tests still pass:
https://github.com/dapphub/dapptools/blob/f24cab707adda124c0035c97e3c54fe8c9bde773/src/dapp/libexec/dapp/dapp#L114

**Comment by d-xo** [comment]
nice catch! ✨

Loading `.dapprc` earlier seems sensible, a pr would be great 😊
