### ISSUE TITLE
dapp test freezes in interesting proxy scenario

### ISSUE THREAD

**Issue by cmditch** [dapphub/dapptools#69]
dapp test is freezing under certain conditions. Once again using the gnosis proxy contract, except this time we have a proxy with a function which creates a contract, which is itself a proxy.

See repo [here](https://github.com/cmditch/hevm-proxy-freeze) where issue can be easily replicated.

See gist of contracts [here](https://gist.github.com/cmditch/e0d97f60cdbd42a75655ab4a0f1767b6), which can easily be popped into remix and tested on JS evm, geth, testnets, etc.

Using binaries:
/nix/store/wgx7xbv387yfljqwyz1sp5j7lv6f5p39-hevm-0.15/bin/hevm
/nix/store/snmiq60r066piwbg0gyv3iaslba66337-dapp-0.9.0/libexec/dapp/dapp

**Comment by cmditch** [comment]
There seems to be a general issue with nesting factories within factories, regardless of using a proxy. Will work on a code example for this.

**Comment by rainbreak** [comment]
Can you try with latest master? There was a nonce issue #70 which was fixed and may be related.

**Comment by cmditch** [comment]
Any tips on building? All I have available atm is a macbook. `stack build` is throwing dependency errors.
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hevm-0.18:
    brick-0.17.2 from stack configuration does not match >=0.18  (latest matching version is 0.40)
    megaparsec-5.2.0 from stack configuration does not match >=6.0  (latest matching version is 6.5.0)
    restless-git must match >=0.7, but the stack configuration has no specified version (no package with that name found, perhaps there is a typo in
                 a package's build-depends or an omission from the stack.yaml packages list?)
    rosezipper must match >=0.2, but the stack configuration has no specified version  (latest matching version is 0.2)
    s-cargot must match >=0.1, but the stack configuration has no specified version  (latest matching version is 0.1.4.0)
    time-1.6.0.1 from stack configuration does not match >=1.8  (latest matching version is 1.9.2)
    tree-view must match ==0.5, but the stack configuration has no specified version  (latest matching version is 0.5)
```

**Comment by rainbreak** [comment]
@cmditch I use `nix-env -f $HOME/src/dapptools -iA dapp hevm` to build from my local

**Comment by cmditch** [comment]
Tests confirmed passing on hevm-0.18 now, thanks!

Using proxies, able to bring gas costs down from 3.3 to 0.2 million.
