### ISSUE TITLE
internal error from HasCallStack

### ISSUE THREAD

**Issue by mbrock** [dapphub/dapptools#7]
<a href="https://github.com/wjmelements"><img src="https://avatars1.githubusercontent.com/u/799573?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wjmelements](https://github.com/wjmelements)**
_Friday Feb 16, 2018 at 23:44 GMT_
_Originally opened as https://github.com/dapphub/hevm/issues/33_

----

This doesn't look helpful, but it's the only error message given.
```
FAIL test_transfer()

hevm: internal error: method type
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:214:22 in hevm-0.12.3-F2xYvHyywk1C4HRq6dL7d:EVM.Solidity
```

**Comment by rainbreak** [comment]
Very outdated by now.
