### ISSUE TITLE
`seth debug` fails if gitconfig has `defaultBranch = main`

### ISSUE THREAD

**Issue by mds1** [dapphub/dapptools#709]
1. First I ran `nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA dapp` to make sure I was using the latest version. 
2. Next I ran `seth debug <txhash>` which failed with:

```
seth-debug: info: fetching contract source from etherscan...
seth-debug: info: transaction (0/212)fatal: Not a valid object name refs/heads/master
hevm: user error (("git",["-C","/tmp/hevm.libs.eYi2D","ls-tree","-r","-z","refs/heads/master"]): exited with code 128)
```

3. I opened my root gitconfig and commented out the line that says `defaultBranch = main`
4. Ran `seth debug <txhash>` again and it worked as expected

**Comment by d-xo** [comment]
oh, I thought that I had fixed this with: https://github.com/dapphub/dapptools/pull/640

Can you try again after running `nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA seth` to make sure that you have the latest version of seth as well as of dapp?

**Comment by mds1** [comment]
Ah, yes I pulled that update command from the related issue (#660) and just realized it only updates dapp. Oops, sorry! 

So I ran that:

```
$ nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA seth
replacing old 'seth-0.10.1'
installing 'seth-0.10.1'
trace: Warning: `stdenv.lib` is deprecated and will be removed in the next release. Please use `lib` instead. For more information see https://github.com/NixOS/nixpkgs/issues/108938
building '/nix/store/1xgspg1r1jsl01b73ivndysgljnjbvjc-user-environment.drv'...
created 32 symlinks in user environment
```

And from the version numbers it seems it re-installed the same version. But running `seth debug <txhash>` afterwards now works, which seems odd?

**Comment by mds1** [comment]
Either way, working now so going to close this issue. Thanks @d-xo!

**Comment by d-xo** [comment]
> And from the version numbers it seems it re-installed the same version. But running seth debug <txhash> afterwards now works, which seems odd?

Oh, I think I just forgot to bump the seth version number in the previous release. My bad.
