### ISSUE TITLE
hevm: no contract definition AST - `dapp debug` quits

### ISSUE THREAD

**Issue by tcoulter** [dapphub/dapptools#712]
Using `dapp debug`, when I press enter to view the Contracts browser, the debug process exits to the console and I receive the following error: 

![image](https://user-images.githubusercontent.com/92629/127062738-9eaeb307-7d5a-4e32-9f17-5b4fd856c1ca.png)

To reproduce: 

1. Clone this repo: https://github.com/tcoulter/sai
2. Run `dapp debug`
3. Choose any test from the list (I was working on `CageTest::testCageExistAfterPeriod()` at the time time)
4. Step into a portion of the code that you do have sources for (e.g., you can see the code highlighted in the bottom left pane). This step is mostly to show that you do have the AST for at least *some* sources. 
5. Hit `Enter` to move to the contracts browser. Notice that the debug process quits, and the above error is shown on your screen. 

Environment: 

- Windows Subsystem for Linux v2 (Ubuntu 20.04.1 LTS)
- dapp 0.33.0
- solc, the solidity compiler commandline interface
- Version: 0.8.6+commit.11564f7e.Linux.g++
- hevm 0.47.0

**Comment by MrChico** [comment]
thanks for the report. fix in https://github.com/dapphub/dapptools/pull/711
