### ISSUE TITLE
functions that return a "bytes" type always revert when testing with "dapp test"

### ISSUE THREAD

**Issue by jparklev** [dapphub/dapptools#72]
## Description
Any function that returns raw `bytes` will yield "error Revert" if tested with `dapp test` regardless of whether the function is valid. 

## Code Example
Check out [this](https://github.com/jparklev/minimal-hevm-issue) repo for a minimal example, below is a snippet

```
contract MinimalHevmIssue {
    function ping() public pure returns (bytes) {
        bytes memory someBytes = new bytes(32);
        return someBytes;
    }
}
```

**Comment by jparklev** [comment]
Ahh seems to be a general limitation of solidity for external contract calls

**Comment by rainbreak** [comment]
@jparklev no this should work now, dynamic return sizes are implemented in `hevm` following the byzantium fork
