### ISSUE TITLE
Missing Semigroup import in restless-git-0.7

### ISSUE THREAD

**Issue by neuromancer** [dapphub/dapptools#73]
A [missing import](https://github.com/dapphub/dapptools/blob/master/src/restless-git/src/Restless/Git.hs#L24) in restless-git-0.7 is causing this issue: 

```
    Configuring restless-git-0.7...
    Building restless-git-0.7...
    Preprocessing library restless-git-0.7...
    [1 of 1] Compiling Restless.Git     ( src/Restless/Git.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Restless/Git.o )
    
    /tmp/stack5196/restless-git-0.7/src/Restless/Git.hs:46:10: error:
        Not in scope: type constructor or class ‘Semigroup’
        Perhaps you want to add ‘Semigroup’ to the import list
        in the import of ‘Data.Semigroup’ (src/Restless/Git.hs:24:1-36).
```

**Comment by andremarianiello** [comment]
How did you even get it to get that far in the build? When I use stack build I get errors about missing extra deps.

**Comment by andremarianiello** [comment]
I believe this happens when you build against a version of base that is not new enough. I think base 4.11 or newer should work.

**Comment by neuromancer** [comment]
> I believe this happens when you build against a version of base that is not new enough. I think base 4.11 or newer should work.

Fair enough. Sorry!
