### ISSUE TITLE
hevm: Segmentation fault when running tests with dapptools 0.48.0 and master

### ISSUE THREAD

**Issue by naszam** [dapphub/dapptools#747]
When running tests with either the last dapptools version 0.48.0 or master (via duppgrade),
I get the following using an alchemy rpc url:
```haskell
Running 17 tests for src/DssSpell.t.sol:DssSpellTest
/nix/store/bknss8mgr3g292xlj73ncwxkjdn07cbm-dapp-0.34.0/libexec/dapp/dapp-test: line 59: 105432 Segmentation fault      (core dumped) hevm dapp-test --dapp-root="${DAPP_ROOT}" --json-file="${DAPP_JSON}" ${opts[@]}
make: *** [Makefile:6: test] Error 139
```

Switching to 0.46.0 works

**Comment by d-xo** [comment]
Thanks for the report! Can you give a link to a repo where we can reproduce this issue?

**Comment by naszam** [comment]
repo: https://github.com/makerdao/spells-mainnet/pull/179

**Comment by brianmcmichael** [comment]
For color, I'll add that this is transient. @naszam and another member of the team were getting consistent segfault errors, but I was using 0.48.0 against a local geth node and didn't get these errors against the same code. Perhaps there's something system-related going on here.

**Comment by TransmissionsDev** [comment]
i've seen segfaults opening the debugger sometimes, usually goes away after just trying again tho

**Comment by TransmissionsDev** [comment]
also pretty cool that y'all are using duppgrade hehe

**Comment by kmbarry1** [comment]
I'm hitting this too, on the current `master` of `dss-charter` (1f309d80078e186504cd4150bd731714d226e39d):
https://github.com/makerdao/dss-charter

```
Running 3 tests for src/test/ProxyManagerClipper-integration.t.sol:ProxyManagerClipperIntegrationTest
/nix/store/0g5glbq80jlqivddgv6hjqxyky93l6q7-dapp-0.34.0/libexec/dapp/dapp-test: line 56: 10207 Segmentation fault      (core dumped) hevm dapp-test --dapp-root="${DAPP_ROOT}" --json-file="${DAPP_JSON}" ${opts[@]}
```

**Comment by kmbarry1** [comment]
Update: repros if I use an Infura endpoint as well.

**Comment by MrChico** [comment]
This is likely a GHC bug. There shouldn't be any way a haskell can segfault unless you're doing some crazy  `unsafePerformIO`, which we don't. The fact that it is mostly triggered with RPC calls and started happening recently makes me think that it might stem from this optimization https://github.com/dapphub/dapptools/commit/f9f5b509ffa40381764313bf5f892068a53174d7

**Comment by MrChico** [comment]
I made a branch `revertopti`, which in case it passes ci I would encourage you to try out and see if it solves these crashes https://github.com/dapphub/dapptools/compare/revertopti

**Comment by naszam** [comment]
Just tried using the branch `revertopti` and the path `dapptools/src/dapp/bin/dapp` and it seems to work with two different rpc urls.

**Comment by MrChico** [comment]
great. Also for you @kmbarry1 ?

**Comment by brianmcmichael** [comment]
I tested `revertopti` also and can confirm that it doesn't appear to introduce any regression errors.

**Comment by MrChico** [comment]
Ok. Merged `revertopti`. Please reopen if the problem persists on master
