### ISSUE TITLE
dapp verify-contract fails with "jays: error in -e"

### ISSUE THREAD

**Issue by transmissions11** [dapphub/dapptools#753]
```
❯ ETHERSCAN_API_KEY=REDACTED dapp verify-contract RolesAuthority 0x9ed0e3fe49af99a8907361d9b7caea8f214fe288
jays: error in -e
```

**Comment by OdysLam** [comment]
It took me solid 30m to find this issue and understand the right syntax. Adding your example in the docs @transmissions11

**Comment by transmissions11** [comment]
> It took me solid 30m to find this issue and understand the right syntax. Adding your example in the docs @transmissions11

ayy thx good idea!

**Comment by transmissions11** [comment]
i wonder if we could update --verify to accept just a contract name like `dapp deploy`... @d-xo ?

**Comment by d-xo** [comment]
I think it should be possible, and I think it sounds like a good idea :slightly_smiling_face:

**Comment by transmissions11** [comment]
> I think it should be possible, and I think it sounds like a good idea :slightly_smiling_face: 

kk will give it a shot!

**Comment by OdysLam** [comment]
@transmissions11 I was thinking in taking a stab at it.

Can we assume that the command is meant to be run inside the directory where the dapptools project lives? Thus, expect source files to live in `/src`, etc.

**Comment by transmissions11** [comment]
> @transmissions11 I was thinking in taking a stab at it.

i've already got a WIP branch for this but if you're gonna frontrun me can you extract the logic into a generic command like `dapp---get-contract` so the same logic can be used across `dapp create`/`dapp verify-contract` and future commands that use `dapp.out.json` data 🙏

**Comment by OdysLam** [comment]
Nah, there is no reason to do double work. There is more than enough features for everyone to go around.

Thanks for picking this up!
