### ISSUE TITLE
Store "failed" variable globally

### ISSUE THREAD

**Issue by CodeSandwich** [dapphub/dapptools#768]
# The situation

The `failed` variable in `test.sol` is stored in every instance of an `is DSTest` contract, but only the instance containing the currently run test is checked when deciding if the test has failed.

# The problem

This makes it very hard to create a test utility using dapptools asserts, which could be used in multiple test contracts. The test utility must inherit from `DSTest`, but its `failed` state won't be checked and all failing asserts will be silently ignored.

# The solution

The `failed` flag should be settable globally. It could be done by pre-deploying a test state contract under a constant address, similiarly to the HEVM cheatcodes contract. Alternatively HEVM cheatcodes' `store` could be used to set a flag in the storage of an existing contract, e.g. in HEVM cheatcodes contract itself.

**Comment by MrChico** [comment]
I'm not sure I understand the description of the problem. Can you describe the scenario where this is problematic in more detail?

**Comment by CodeSandwich** [comment]
Sure. In my particular case it was nothing fancy, I wanted to add some invariant checks to a test user contract (`MyContractUser`, which forwards all calls to an underlying contract). It turned out that I can't do that and I need to extract all assertion logic to the test contract. It's not a blocker, but it forces bad code structure.

Another example are all sorts of universal assertion tools like checking that two lists are equivalent. They require either copying code to each test contract or exposing some bubbling mechanism for setting `failed` in the root test contract. Again, not a blocker, but needlessly complicates code.

The behavior of `failed` is also just an unpleasantly surprising to newcomers like me. It's like in no other testing framework forcing unprecedented practices, its behavior isn't documented and it's breaking tests silently.

**Comment by d-xo** [comment]
Apologies @CodeSandwich, I'm still not sure I fully understand, could you perhaps link to some examples of what you want to do that's not possible with the current implementation?

**Comment by CodeSandwich** [comment]
No problem, consider this code:
```solidity
contract MyContract {
    function foo(uint arg) public returns (uint) {
        // do stuff
        return arg + 2;
    }
}

contract MyContractUser is DSTest {
    MyContract immutable myContract;

    constructor() {
        myContract = new MyContract();
    }

    function foo(uint arg) public returns (uint ret) {
        ret = myContract.foo(arg);
        assertEq(ret, arg + 1, "Invariant failed"); // Always violated, should fail
    }
}

contract MyContractTest is DSTest {
    function testFoo() public {
        MyContractUser user = new MyContractUser();
        // do stuff
        uint fooRet = user.foo(123);
        // do more stuff
    }
}
```
The `assertEq` here doesn't work. The invariant it's checking is always violated, but the test always passes. If the code is refactored so `assertEq` is moved to `MyContractTest`, it nicely fails as expected:
```solidity
contract MyContractTest is DSTest {
    function testFoo() public {
        MyContractUser user = new MyContractUser();
        // do stuff
        uint fooRet = user.foo(123);
        assertEq(fooRet, 123 + 1, "Invariant failed");
        // do more stuff
    }
}
```
```
Failure: testFoo
  
  Error: "Invariant failed"
  Error: a == b not satisfied [uint]
    Expected: 124
      Actual: 125
```

**Comment by d-xo** [comment]
Ah I see. Yes this is a little surprising and having a global `failed` seems to be a valid solution :+1:

**Comment by d-xo** [comment]
Fixed in https://github.com/dapphub/ds-test/pull/30
