### ISSUE TITLE
Do not run tests in abstract contracts

### ISSUE THREAD

**Issue by CodeSandwich** [dapphub/dapptools#769]
Writing `abstract contract MyTest is DSTest {` derails the testing suite:

```
Running 1 tests for src/test/MyTest.t.sol:MyTest
hevm: Data.Binary.Get.runGet at position 0: not enough bytes
uint256
bool
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:351:5 in binary-0.8.8.0:Data.Binary.Get
```

AFAIK there's no way to tell the testing suite to ignore a contract. It's included for running even before attempted compilation based on the ABI and there's no way to hide `IS_TEST`.

**Comment by d-xo** [comment]
nice catch! I think we can fix this by only executing test contracts that actually have code.
