### ISSUE TITLE
`mapfile` not present on Mac OS

### ISSUE THREAD

**Issue by Jasagredo** [dapphub/dapptools#78]
Mac OS is shipped using an older version of bash so it doesn't have some commands that are built-in in Bash 4. That's the case of `mapfile`.

This is the reason why `dapp init` terminates with a failure caused by `dapp test` that is using such function. The error it rises is this one:

```
/usr/local/libexec/dapp/dapp-build: line 19: mapfile: command not found
/usr/local/libexec/dapp/dapp---find-libraries: line 17: mapfile: command not found
```

On the other hand, running `hevm dapp-test` runs successfully all the tests without using `mapfile`.

Maybe this should be taken into account in future versions and use a different method if the system is Mac OS.

**Comment by rainbreak** [comment]
There was an intentional upgrade from bash 3 -> 4 when we started packaging with nix. There are more bash 4 features than `mapfile` being used I think. Are you reluctant to use bash 4 locally?

**Comment by Jasagredo** [comment]
I kinda like ZSH which seems to be _equivalent_ to Bash 3 (correct me if I'm wrong) and also every macOS is shipped with Bash 3. That's really the only reason.

**Comment by asymmetric** [comment]
Isn’t this supposed to be solved by nix?? Don’t we depend on the version of bash we need, both on Mac and Linux? There might be something wrong with out derivation if that error pops up.

**Comment by rainbreak** [comment]
@Jasagredo bash 4 should be installed along with nix and `dapp` should link to it specifically.

@asymmetric it is possible to install e.g. `dapp` individually using the Makefile in its source. I do it this way with both `dapp` and `hevm` for hacking them locally.

**Comment by Jasagredo** [comment]
I indeed installed dapp using the Makefile. I will test the nix installation on macOS to see if bash4 is installed.

**Comment by rainbreak** [comment]
@Jasagredo can you confirm how the nix install worked for you?

**Comment by asymmetric** [comment]
What’s the advantage of supporting the Makefile build approach?

**Comment by rainbreak** [comment]
> What’s the advantage of supporting the Makefile build approach?

@asymmetric it's easy to do, presents a back to basics alternative to nix-maximalism, and honestly makes my life easier as I can make changes to dapp/seth/hevm on the fly without having to do a nix install each time (by using `make link`). I just don't find nix very ergonomic for this.

**Comment by Jasagredo** [comment]
The nix install worked and now I can run `dapp test` freely. It's strange as I don't seem to be able to run bash4 (if I run `bash` it's `bash 3.2` and there are no more binaries named bash or similar).
