### ISSUE TITLE
seth debug --fast/--unsound

### ISSUE THREAD

**Issue by transmissions11** [dapphub/dapptools#789]
Should add a --fast/--unsound flag to `seth debug` that just uses `run-tx` with `bundle-source` to quickly debug a tx. 

@mds1 implemented this here: https://gist.github.com/mds1/3f070676129a095dec372c2d02cedfdd#file-ethrc-sh-L85, would be dope to upstream

**Comment by d-xo** [comment]
wondering if this belongs in `seth debug` or if we should instead add a `seth run-tx --fetch`? We could even make this the default behaviour for `seth run-tx` if `ETHERSCAN_API_KEY` is set?

**Comment by mds1** [comment]
I think either approach is ok, as long as the net effect is an easier way to debug without needing to manually bundle source and remove the files afterwards. The shortest path to do that while keeping the conveniences of `seth debug` seems to be just adding a flag to skip the transaction simulations in `seth debug`.

But now that I think of it, if you bundle source and run `seth run-tx --trace`, will you get a prettier/friendlier trace than if you didn't bundle source? If so, then I'd agree with @d-xo that we should move the bundling into `seth run-tx`. If not, I don't think it makes a big difference and I'd be ok with either approach

**Comment by d-xo** [comment]
> But now that I think of it, if you bundle source and run seth run-tx --trace, will you get a prettier/friendlier trace than if you didn't bundle source?

Yes, good point. If we have the compiiler output json we can decode events, custom erorrs and contract calls. e.g. [`0x41ccbab4d7d0cd55f481df7fce449986364bf13e655dddfb30aa9b38a4340db7`](https://etherscan.io/tx/0x41ccbab4d7d0cd55f481df7fce449986364bf13e655dddfb30aa9b38a4340db7) without the compiler output:

```sh
< seth run-tx 0x41ccbab4d7d0cd55f481df7fce449986364bf13e655dddfb30aa9b38a4340db7 --trace
create <unknown contract>@0x28d2DF1E3481Ba90D75E14b9C02cea85b7d6FA2C <no source map>
 └╴← 11293 bytes of code
call 0x28d2DF1E3481Ba90D75E14b9C02cea85b7d6FA2C::0x485cc9550000000000000000000000007fa7df4996ac59f398476892cfb195ed38543520000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 <no source map>
 └╴← 0x
log3(0xd3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9, 0xffffffffffffffffffffffffffffffffffffffff and 0xffffffffffffffffffffffffffffffffffffffff and 0x7fa7df4996ac59f398476892cfb195ed38543520, 0xffffffffffffffffffffffffffffffffffffffff and 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 and 0xffffffffffffffffffffffffffffffffffffffff, 0x00000000000000000000000028d2df1e3481ba90d75e14b9c02cea85b7d6fa2c000000000000000000000000000000000000000000000000000000000000c9eb) <no source map>
0x00000000000000000000000028d2df1e3481ba90d75e14b9c02cea85b7d6fa2c
```

and with:

```sh
> seth run-tx 0x41ccbab4d7d0cd55f481df7fce449986364bf13e655dddfb30aa9b38a4340db7 --source=tmp.json --trace
create UniswapV2Pair@0x28d2DF1E3481Ba90D75E14b9C02cea85b7d6FA2C (./UniswapV2Factory.sol:419)
 └╴← 11293 bytes of code
call UniswapV2Pair::initialize(address,address)(@0x7FA7dF4996AC59F398476892cfB195eD38543520, @0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2) (./UniswapV2Factory.sol:421)
 └╴← 0x
PairCreated(UniswapV2Pair@0x28d2DF1E3481Ba90D75E14b9C02cea85b7d6FA2C, 51691) (./UniswapV2Factory.sol:425)
0x00000000000000000000000028d2df1e3481ba90d75e14b9c02cea85b7d6fa2c
```

**Comment by transmissions11** [comment]
> Thoughts on making this the default for `run-tx` if `ETHERSCAN_API_KEY` is present?

love it 👍

**Comment by mds1** [comment]
Awesome, so it sounds like moving the bundling into `run-tx` is the way to go. Making it the default when an Etherscan API key is present seems like no downside, so I'm in favor of that also
