### ISSUE TITLE
ds-tests breaks when using solc 0.5.0

### ISSUE THREAD

**Issue by Jasagredo** [dapphub/dapptools#79]
When updating to 0.5.0 solc, the library breaks as it expects other compiler to be installed. `dapp init` initializes a new project considering the version of solc that is installed in the system. 

Wouldn't it be possible to develop a strategy for handling breaking changes in solidity? Maybe when two solidity versions are _standard_ at the same time, maintain two branches in the repo and choose depending on the system version of solidity.

**Comment by Jasagredo** [comment]
This issue is related with the ds-test repo, but I thought the process should be handled inside `dapp init`

**Comment by asymmetric** [comment]
@rainbreak didn't we add 0.5.0 [here](https://github.com/dapphub/dapptools/commit/be2febd425e6d05cefed0761a4da8a904b7625e7)?

**Comment by rainbreak** [comment]
@asymmetric yes, but dappsys isn't working with 0.5.0 yet so `dapp test` and `dapp init` are failing.

**Comment by nanexcool** [comment]
With @rainbreak updating dappsys, this is working:

`dapp --use solc:0.5.0 init`
