### ISSUE TITLE
DSTest: Failing to transfer ether from test runner

### ISSUE THREAD

**Issue by shazow** [dapphub/dapptools#815]
I've been trying to figure out how to give addresses some ether to play with, and based on https://github.com/dapphub/dapptools/tree/master/src/dapp#unit-testing it seems like `address.transfer(amount)` should do the trick, but my basic test is reverting:

```console
$ dapp test -v
Running 1 tests for src/Bug.t.sol:BugTest
[BAIL] setUp()

Failure: setUp
  src/Bug.t.sol:BugTest
   ├╴constructor
   └╴setUp()
      ├╴create Bug@0xCe71065D4017F316EC606Fe4422e11eB2c47c246 (src/Bug.t.sol:12)
      │  └╴← 63 bytes of code
      ├╴call Bug::[fallback function](0x) (src/Bug.t.sol:13)
      │  └╴error Revert 0x (src/Bug.sol:3)
      └╴error Revert 0x (src/Bug.t.sol:13)
```

Relevant code:

```solidity
contract BugTest is DSTest {
    Bug b;

    function setUp() public {
        b = new Bug();
        payable(address(b)).transfer(42 ether);
    }

    function testBalance() public {
        assertEq(address(b).balance, 42 ether);
    }
}
```

Full reproduction repo here: https://github.com/shazow/dapptools-bug-repro/tree/fccc923bf8509524d82310845cee042fed2b5de5

Apologies if I'm missing a documented step.

**Comment by transmissions11** [comment]
Does `Bug` have a `payable` fallback function? If not I'm pretty sure this is expected behavior?

**Comment by shazow** [comment]
@transmissions11 Ah you're totally right! I forgot solidity added this requirement, been a while. :)

Also I noticed the tutorial does have that in the example, and I could have sworn I tried it but I guess I messed it up. Thank you!
