### ISSUE TITLE
Add a ds-diamond

### ISSUE THREAD

**Issue by mudgen** [dapphub/dapptools#839]
dapp.tools provides a ds-proxy contract.  It would be really great if it also provided a diamond implementation: ds-diamond.

Info about EIP-2535 Diamonds here: https://eips.ethereum.org/EIPS/eip-2535
Intro article: https://eip2535diamonds.substack.com/p/introduction-to-the-diamond-standard
List of projects using diamonds: https://eip2535diamonds.substack.com/p/list-of-projects-using-eip-2535-diamonds

**Comment by d-xo** [comment]
No plans to add this.
