### ISSUE TITLE
Run functional tests when building

### ISSUE THREAD

**Issue by asymmetric** [dapphub/dapptools#84]
To make sure that new versions of the dapptools work, we should run a subset of their functionality as part of the build process.

Examples:

- [x] `nix-build -A solc-versions.solc_$NEWVERSION` #101 
- [ ] spin up a dapp testnet
- [ ] Deploy a meaningful contract compiled with the last couple of solc versions (at least 0.4.24 and 0.5.0)
- [ ] Send txs to it, then read from it
- [ ] Contract should have a payable function, as well as functions that take in bytes and address[] to force solc 0.5.0 to force tagging them with memory or calldata

**Comment by rainbreak** [comment]
`dapp selftest` already does some of this, so just extend that?

**Comment by asymmetric** [comment]
`dapp selftest` runs `dapp test` on a bunch of repos.

I think we should test `seth` as well, and for that some kind of  test abstraction would be nice (e.g. `assert`).

**Comment by MrChico** [comment]
Kinda addressed by #417 , closing
