### ISSUE TITLE
dapp test throwing hevm error

### ISSUE THREAD

**Issue by namrapatel** [dapphub/dapptools#851]
I'm using the dapptools template created by @gakonst (found here: https://github.com/gakonst/dapptools-template), and running `make test` and getting the following error:

hevm: invalid character at offset: 4036
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:538:13 in hevm-0.48.1-68JBNYehi12HotjGf8Zowl:EVM.Solidity
make: *** [test] Error 1

I'm also getting the same error when running `dapp test`, but when I run `dapp build`, I get a few warnings, no error, but my tests return no results. Anyone have any ideas?

**Comment by transmissions11** [comment]
are you trying to use any libraries?

**Comment by namrapatel** [comment]
The codebase has the following devDependencies:

`"devDependencies": {
        "@iarna/toml": "^2.2.5",
        "@latticeprotocol/registry": "^0.0.7",
        "@opengsn/contracts": "^2.2.2",
        "@opengsn/dev": "^2.2.2",
        "@typechain/ethers-v5": "^7.2.0",
        "@typechain/hardhat": "^2.3.1",
        "@types/chai": "^4.2.14",
        "@types/inquirer": "^8.1.3",
        "@types/mocha": "^8.2.0",
        "@types/node": "^14.14.22",
        "chai": "^4.2.0",
        "chai-ethers": "^0.0.1",
        "chalk": "^4.1.2",
        "cli-ux": "^5.6.3",
        "cosmiconfig": "^7.0.0",
        "cross-fetch": "^3.1.4",
        "dotenv": "^9.0.2",
        "ethereum-waffle": "^3.2.2",
        "ethers": "^5.4.7",
        "execa": "^5.1.1",
        "inquirer": "^8.2.0",
        "inquirer-prompt-suggest": "^0.1.0",
        "listr2": "^3.12.2",
        "mocha": "^8.2.1",
        "netlify": "^8.0.2",
        "snarkjs": "https://github.com/justinglibert/snarkjs.git",
        "solhint": "^3.0.0",
        "ts-dedent": "^2.0.0",
        "ts-generator": "^0.1.1",
        "ts-node": "^8.10.2",
        "typechain": "^5.2.0",
        "typescript": "^3.9.7",
        "uuid": "^8.3.2",
        "web3.storage": "^3.3.2",
        "yup": "^0.32.9"
    },
`

But the test is just `Dapptutorial.t.sol` from the dapptools tutorial, which imports nothing.

**Comment by namrapatel** [comment]
> are you trying to use any libraries?

The codebase has the following devDependencies:

`"devDependencies": {
        "@iarna/toml": "^2.2.5",
        "@latticeprotocol/registry": "^0.0.7",
        "@opengsn/contracts": "^2.2.2",
        "@opengsn/dev": "^2.2.2",
        "@typechain/ethers-v5": "^7.2.0",
        "@typechain/hardhat": "^2.3.1",
        "@types/chai": "^4.2.14",
        "@types/inquirer": "^8.1.3",
        "@types/mocha": "^8.2.0",
        "@types/node": "^14.14.22",
        "chai": "^4.2.0",
        "chai-ethers": "^0.0.1",
        "chalk": "^4.1.2",
        "cli-ux": "^5.6.3",
        "cosmiconfig": "^7.0.0",
        "cross-fetch": "^3.1.4",
        "dotenv": "^9.0.2",
        "ethereum-waffle": "^3.2.2",
        "ethers": "^5.4.7",
        "execa": "^5.1.1",
        "inquirer": "^8.2.0",
        "inquirer-prompt-suggest": "^0.1.0",
        "listr2": "^3.12.2",
        "mocha": "^8.2.1",
        "netlify": "^8.0.2",
        "snarkjs": "https://github.com/justinglibert/snarkjs.git",
        "solhint": "^3.0.0",
        "ts-dedent": "^2.0.0",
        "ts-generator": "^0.1.1",
        "ts-node": "^8.10.2",
        "typechain": "^5.2.0",
        "typescript": "^3.9.7",
        "uuid": "^8.3.2",
        "web3.storage": "^3.3.2",
        "yup": "^0.32.9"
    },
`

But the test is just `Dapptutorial.t.sol` from the dapptools tutorial, which imports nothing.

**Comment by namrapatel** [comment]
Shoutout to @transmissions11, this issue can be solved by enabling and properly using `DAPP_LIBRARIES`. I was using a dapptools template, so this fix in particular saved me: https://github.com/gakonst/dapptools-template/pull/34/files
