### ISSUE TITLE
hevm flatten fails when using destructed imports

### ISSUE THREAD

**Issue by ncitron** [dapphub/dapptools#852]
Any file that I attempt to flatten that includes imports of the form:
```
import { ContractName } from "path/to/contract.sol";
```

Will fail with the error:
```
hevm: no refDec for ident/userdef: 797
CallStack (from HasCallStack):
  error, called at src/EVM/Flatten.hs:447:14 in hevm-0.48.1-KdjyJ1kXYK7IQeiBwTCoFo:EVM.Flatten
```

As a temporary workaround, you can properly flatten the contracts using imports of the form:
```
import "path/to/contract.sol"
```
But this solution is suboptimal as it makes it impossible to handle naming conflicts.

**Comment by transmissions11** [comment]
cannot reproduce in the Rari Vaults repo 🤔

**Comment by ncitron** [comment]
This bug cannot be reproduced in solidity 0.8.9, but I have confirmed it with a minimal test of 0.6.10

**Comment by d-xo** [comment]
@ncitron do you have a repo we can use to reproduce this issue? I would assume that this is down to some difference in the solidity ast format between 0.6.10 and 0.8.10.

**Comment by guifel** [comment]
I confirm this bug in Solidity 0.6.7
