### ISSUE TITLE
DappTools takes far too long to install

### ISSUE THREAD

**Issue by daweth** [dapphub/dapptools#878]
```curl https://dapp.tools/install | sh``` is taking over 30 minutes to install . Is this normal behavior?

**Comment by daweth** [comment]
Update:

the installation is stuck on `[ 2 of 32] Compiling EVM.FeeSchedule  ( src/EVM/FeeSchedule.hs, dist/build/EVM/FeeSchedule.o, dist/build/EVM/FeeSchedule.dyn_o )`

**Comment by MrChico** [comment]
no, this means you have a cachix problem

**Comment by daweth** [comment]
@MrChico , not sure what that is. How do I fix it?

**Comment by septaplex** [comment]
@daweth are you sitting behind a firewall or do you have some other security measures in place?

I saw the same issue with a machine that had "security software" installed (which blocks some domains) the other day.

**Comment by daweth** [comment]
None that I’m aware of. Btw, I’m using the latest version of MacOS with a m1 max

**Comment by septaplex** [comment]
Yeah, I run an Intel Mac however I also do run the latest version of macOS 12.0.1.

Oddly enough Dapp Tools `c43ea2a6240b6e49c0b79b067ab703e018f617c8` runs without any issues.

**Comment by REGO350** [comment]
I have the same issue here on M1 mac. Terminal running under rosetta but gets stuck at `[ 2 of 32] Compiling EVM.FeeSchedule  ( src/EVM/FeeSchedule.hs, dist/build/EVM/FeeSchedule.o, dist/build/EVM/FeeSchedule.dyn_o )`.

**Comment by REGO350** [comment]
Ok, found the solution. Install older version of nix:
https://releases.nixos.org/?prefix=nix/

I installed nix-2.3.16-x86_64-darwin.tar.xz

**Comment by septaplex** [comment]
Thanks for providing a fix @REGO350 :+1:

Hmm that's a little bit unfortunate (I use Nix as my main package manager on macOS). Hopefully DappTools will work with newer Nix versions soon.

**Comment by daweth** [comment]
thanks for the fix. I recommend using a combination of docker and an older version of nix to achieve the same result.

**Comment by pyk** [comment]
I have the same issue, as @REGO350 mentioned installing the older version of Nix solved the problem.

U can simply use the following command to install Nix specific version:

```
curl -L https://releases.nixos.org/nix/nix-2.3.16/install | sh
```

**Comment by daweth** [comment]
This doesn't work. 

```
I am executing:

    $ sudo mkdir -pv -m 0755 /nix /nix/var /nix/var/log /nix/var/log/nix /nix/var/log/nix/drvs /nix/var/nix /nix/var/nix/db /nix/var/nix/gcroots /nix/var/nix/profiles /nix/var/nix/temproots /nix/var/nix/userpool /nix/var/nix/gcroots/per-user /nix/var/nix/profiles/per-user

to make the basic directory structure of Nix (part 1)

mkdir: /nix: Read-only file system
mkdir: /nix/var: Read-only file system
mkdir: /nix/var/log: Read-only file system
mkdir: /nix/var/log/nix: Read-only file system
mkdir: /nix/var/log/nix/drvs: Read-only file system
mkdir: /nix/var/nix: Read-only file system
mkdir: /nix/var/nix/db: Read-only file system
mkdir: /nix/var/nix/gcroots: Read-only file system
mkdir: /nix/var/nix/profiles: Read-only file system
mkdir: /nix/var/nix/temproots: Read-only file system
mkdir: /nix/var/nix/userpool: Read-only file system
mkdir: /nix/var/nix/gcroots/per-user: Read-only file system
mkdir: /nix/var/nix/profiles/per-user: Read-only file system

```

**Comment by piavgh** [comment]
@daweth : hi, did you find the solution for this? I have the same issue on Macbook Pro 2019 (not M1)

**Comment by jokerstudio** [comment]
I have the same issue,
Someone solved this problem or solution for this?
```
[ 1 of 32] Compiling EVM.Demand       ( src/EVM/Demand.hs, dist/build/EVM/Demand.o, dist/build/EVM/Demand.dyn_o )
[ 2 of 32] Compiling EVM.FeeSchedule  ( src/EVM/FeeSchedule.hs, dist/build/EVM/FeeSchedule.o, dist/build/EVM/FeeSchedule.dyn_o )
```

**Comment by daweth** [comment]
@piavgh @jokerstudio just use foundry, it has much better support
