### ISSUE TITLE
How to fake call from a different msg.sender?

### ISSUE THREAD

**Issue by xphoniex** [dapphub/dapptools#880]
I'm trying to test from user side, thus need to fake a call from a user address e.g. 0x02, is it possible now?

**Comment by MrChico** [comment]
Yes, `DAPP_TEST_CALLER` or the make a user contract. Please use dapphub.chat for questions like this

**Comment by xphoniex** [comment]
I signed up on dapphub.chat with email hours ago and still haven't received the confirmation mail.

**Comment by transmissions11** [comment]
Use Twitter auth
