### ISSUE TITLE
feature request: add almost equal

### ISSUE THREAD

**Issue by ada173** [dapphub/dapptools#905]
It would be nice if it has almost eq assert like [chai-almost](https://www.chaijs.com/plugins/chai-almost/)

**Comment by transmissions11** [comment]
we have approxeq in here https://github.com/Rari-Capital/solmate/blob/main/src/test/utils/DSTestPlus.sol

**Comment by ada173** [comment]
> we have approxeq in here https://github.com/Rari-Capital/solmate/blob/main/src/test/utils/DSTestPlus.sol

thank you! it reallyly helps

**Comment by d-xo** [comment]
This is a feature request for `ds-test` not dapptools.
