### ISSUE TITLE
Nix installation process is broken for MacOS

### ISSUE THREAD

**Issue by platocrat** [dapphub/dapptools#914]
## Issue
Upon comparing the official NixOS installation steps to the steps outlined in the dapptools' README.md, it seems the current Nix installation step is outdated.

## Solution
Replace current installation step to install Nix with a link to [NixOS's official installation page](https://nixos.org/download.html#nix-install-linux) (this link is for Linux, and [this link](https://nixos.org/download.html#nix-install-macos) is for MacOS).

Explain that they can choose the proper installation command to run (from NixOS's site) based on their OS.

**Comment by Matthelonianxl** [comment]
https://github.com/NixOS/nixpkgs

**Comment by d-xo** [comment]
Thanks! Fixed in #928
