### ISSUE TITLE
Unable to change solc version using by dapp

### ISSUE THREAD

**Issue by maham-zaidi** [dapphub/dapptools#920]
Hi. I am using ubuntu 21 LTS version and trying to compile and run pickle.finance contracts using dapp.tools. The steps are mentioned here https://github.com/pickle-finance/protocol. I followed till the command **dapp build** upon which it gave me different compiler version error. But that was because dapp was using solc version 0.8.6 whereas the contracts needed to be compiled which version 0.6. I used these two commands:
```
dapp --use solc:0.6.0 build
nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_6_0
```
to try to make dapp use verion 6 but after running dapp -version it still gives the following output
```
dapp 0.35.0

solc, the solidity compiler commandline interface

Version: 0.8.6+commit.11564f7e.Linux.g++

hevm 0.49.0
```

I need help on how to make it use version 6. Attaching screenshot of some of the errors:

![image](https://user-images.githubusercontent.com/39157262/157383307-5284ef93-4f65-4bc9-9c49-d758ee59af06.png)

**Comment by d-xo** [comment]
You are using 0.6.0 on a contract that needs 0.6.7.
