### ISSUE TITLE
'dapp2' missing, at /nix/store/.../nix/solidity-package.nix:23:19

### ISSUE THREAD

**Issue by gbalabasquer** [dapphub/dapptools#921]
Shouldn't this line be removed after `dapp2` was deleted:
https://github.com/dapphub/dapptools/blob/master/nix/solidity-package.nix#L23?

Commit: https://github.com/dapphub/dapptools/commit/850ce46528ec2c1425c0de63e24e86767471849b

**Comment by gbalabasquer** [comment]
@d-xo sorry to tag you, just want to make sure what I'm reporting makes sense it is actually a bug. Not really sure either if the fix would be just removing the line or actually having to export something different.

**Comment by d-xo** [comment]
nice catch, I think this should be fixed in #929.
