### ISSUE TITLE
more explicit installer instructions/support?

### ISSUE THREAD

**Issue by abathur** [dapphub/dapptools#922]
Hi all. I noticed [a perplexing install issue opened against Nix](https://github.com/NixOS/nix/issues/6226) and traced the steps they were following back to this repo. It looks like the user is just copy/pasting all of the Nix install codeblock into their terminal at once. 

I imagine this specific confusion is rare, but anything you can do to catch cases like it is appreciated!

**Comment by karmabadger** [comment]
hmmm I think in this case, the user might need to get familiar with linux bash first

**Comment by d-xo** [comment]
I think this should be fixed by #928
