### ISSUE TITLE
dapptools only works on nix 2.5.1

### ISSUE THREAD

**Issue by pyk** [dapphub/dapptools#923]
When I tried to install dapptools on my fresh ubuntu, I discovered that dapptools only works perfectly with nix 2.5.1.

These are the problems that I encounter when using nix 2.6.x and 2.7.x

```
checking for references to /build/ in /nix/store/gbgnx6pc1yfccbbgva4ilajhfkvrnlhw-solc-static-0.8.11...
automatically fixing dependencies for ELF files
searching for dependencies of /nix/store/gbgnx6pc1yfccbbgva4ilajhfkvrnlhw-solc-static-0.8.11/bin/.solc-0.8.11-wrapped
error: file 'REPEAT' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at /nix/store/cz726jh79y4vciyvxx1q5kg3mi84zliw-env-manifest.nix:1:2732:
```

So instead of installing the latest version of nix, I use nix 2.5.1:

```
sh <(curl -L https://releases.nixos.org/nix/nix-2.5.1/install) --no-daemon
curl https://dapp.tools/install | sh
```

Related issue: 

- https://github.com/smartcontractkit/dapptools-starter-kit/issues/2

**Comment by d-xo** [comment]
Looks like this is an issue with nix itself rather than dapptools? I think it should fix itself once https://github.com/NixOS/nix/pull/6296 is backported to 2.7. 

Am I missing something?

**Comment by pyk** [comment]
@d-xo yes I believe so
