### ISSUE TITLE
Development of HEVM will continue?

### ISSUE THREAD

**Issue by ggrieco-tob** [dapphub/dapptools#931]
Given the fact that "dapptools is currently in a stage of clandestine development", and that a tool like [Echidna](https://github.com/crytic/echidna/) relies on HEVM, we were wondering how long it will be supported with new EVM hard forks and QOL fixes.

**Comment by d-xo** [comment]
Work on hevm is continuing, with development supported by the FV team at the EF.

**Comment by d-xo** [comment]
To expand on this point a bit, dapptools is not abandoned, but we are deprioritising end user support and devx considerations in favour of leveling up the symbolic analysis capabilities of hevm.

The foundations for this work can be seen in the `expression-language` branch, which contains a fairly extensive refactor of the core EVM datatypes (check [here](https://github.com/dapphub/dapptools/blob/expression-language/src/hevm/src/EVM/Types.hs#L127)). Over time we intend to build on these new representations to build an upgraded bytecode equivalence checking engine / symbolic model checker for [act](https://github.com/ethereum/act).

@ggrieco-tob if ToB has changes that they would like to upstream that would be beneficial for echidna I would be happy to review them.

**Comment by ggrieco-tob** [comment]
Thanks for the clarification, happy to see dapp and hevm maintained. We don't any HEVM changes for upstream so far, but we will check if there is anything particular in the near future.
