### ISSUE TITLE
Document "pkg update"

### ISSUE THREAD

**Issue by asymmetric** [dapphub/dapptools#94]
```
❯ dapp pkg
dapp package manager...
current directory: /home/asymmetric/.dapp/dapptools

Options:
  init
  list
  install <package>
  uninstall <package>
  selfupdate
```

`dapp pkg update` is actually supported, but not mentioned above, which can be confusing.

**Comment by iamchrissmith** [comment]
I'll take this one next (I don't see code already written for it so might give me a little more warm up thatn #33 :-) )
