### ISSUE TITLE
stuck installing "EVM.FeeSchedule" on OSX at 100% CPU

### ISSUE THREAD

**Issue by msmyers** [dapphub/dapptools#951]
```
Preprocessing library for hevm-0.49.0..
Building library for hevm-0.49.0..
[ 1 of 32] Compiling EVM.Demand       ( src/EVM/Demand.hs, dist/build/EVM/Demand.o, dist/build/EVM/Demand.dyn_o )
[ 2 of 32] Compiling EVM.FeeSchedule  ( src/EVM/FeeSchedule.hs, dist/build/EVM/FeeSchedule.o, dist/build/EVM/FeeSchedule.dyn_o )
```

**Comment by frankwei98** [comment]
me too. I am using macOS Monterey 12.2.1 with Intel chip.
and now `[ 2 of 32] Compiling EVM.FeeSchedule` takes forever in my Macbook.

**Comment by frankwei98** [comment]
I solved this problem by uninstall nixos and reinstall with a elder version.
Reference:
https://github.com/dapphub/dapptools/issues/878#issuecomment-995543586

**Comment by asymmetric** [comment]
hevm now lives at https://github.com/ethereum/hevm, please raise the issue there if still relevant.
