### ISSUE TITLE
Can not install dapp by nix on mac

### ISSUE THREAD

**Issue by Skyge** [dapphub/dapptools#971]
When try to install dapp by the command
```
nix profile install github:dapphub/dapptools#dapp --extra-experimental-features nix-command --extra-experimental-features flakes
```
got an error for `ethsign-0.17.1-go-modules` like this:

![image](https://user-images.githubusercontent.com/27282380/218982878-363da360-1f4c-4b93-9d18-6fd9ab912705.png)

Use a proxy(Clash) on my mac.

MacOs: 13.2.1
Nix: 2.13.2

**Comment by asymmetric** [comment]
It looks like an issue with your network. Just try again?
